s3config.release.yaml, s3config.yaml
=> EOS-13582: Increase RPC message size from 256K to 512K

server/s3_get_bucket_action.cc, server/s3_get_bucket_action.h
Description:
The last_key is set to the actual last element of the fetched result set, instead of setting it
in different logical conditions. This is done to avoid any situation of last_key being not set properly, thereby causing
repetitive same keyset fetch and causing request timeout.
=> EOS-13706: Fix for object listing getting timeout

scripts/s3-support-bundles/s3_bundle_generate.sh
Provisioner made changes in core directory location .. hence we have updated same in our support bundle
old    : /var/crash
New : /var/log/crash
=> [LDR-R1]EOS-13808:s3:crash directory location updation in support bundle

scripts/provisioning/setup.yaml
Preserve jks files in node replacement
Two files needs to be preserved or copied to another node after node replacement
- /opt/seagate/cortx/auth/resources/s3authserver.jks
- /opt/seagate/cortx/auth/resources/keystore.properties
=> EOS-14069:Auth : Node replacement should preserve jksstore and keystore file

orchastrator.sh
Issue:
Recovery script exited with description
"device-mapper: create ioctl on vg_metadata_srvnode--2-MD_Snapshot
LVM-x8S3hpJ1KvhcpXuuPRBlunRYM70m332wdiytMJXGbdDqauX4uRhmXFAr48osxJh7
failed: Device or resource busy"
Snapshot is not able to be delete because it's present in multipath device.
Due to last executed recovery device caches.
Fix:
Add print for requesting to reboot all the nodes at the end of recovery
to clean all the caches for the device
=> EOS-13841: fix failed to remove snapshot during  datarecovery

server/s3_put_object_action.cc, server/s3_put_object_action.h, ut/s3_put_object_action_test.cc
Put object was returning 200 even if motr set state to "failed", becasue
we were only checking "failed_to_launch" state in the callback. Added else
condition to return InternalError for all other states in the callback for failure.
=> EOS:14187: [LDR R1] handle error scenario in callback: save_object_metadata_failed

mempool/s3_memory_pool.c
=> [LDR-R1]EOS-14148: Memory pool alignment is displayed incorrectly

scripts/env/common/create-cortx-repo.sh
Update path for build dependencies of github release for s3server 
Old values : https://github.com/Seagate/cortx-s3server/releases 
New  values : https://github.com/Seagate/cortx/releases/tag/build-dependencies
=> EOS-14371:S3:Update repourl for dependency pkgs

dev-starts3.sh, s3config-test.yaml, s3config.release.yaml, s3config.yaml, server/s3_option.cc, server/s3_option.h, system/s3startsystem.sh, ut/s3_option_test.cc
I have added a new config parameter in s3config.yaml to read it in s3server
startup script, and add "--addb" option, if the new conf parameter is set.
=> EOS-14281: [LDR R1] Enable addb dump for s3server by default.

.github/workflows/triage.yml
Signed-off-by: Gaurav Chaudhari <gaurav.chaudhari@seagate.com>
Triage is an important part of open source. It can be difficult to keep up with the issues as the size of a project grows, the demands placed on the maintainers grow. This means they are forced to choose between spending enormous amounts of time reviewing each GitHub issue, only skimming over issues, or worse, ignoring issues.
Triage action can help an open-source project by labeling newly opened issues as `needs-triage`. So, maintainers could easily filter out all unattended/missed issues and label them appropriately in triage meetings. Now, it would be easy for a specific group of maintainers to filter out issues of their expertise/interest and start reviewing it in a timely manner.
=> [GitHub Action]  Issue triage

CODE_OF_CONDUCT.md
Reverts Seagate/cortx-s3server#364
Added back CODE_OF_CONDUCT.md
- .git folder does not seem to work, adding back the file
=> Revert "Delete CODE_OF_CONDUCT.md"

server/s3_post_complete_action.cc, server/s3_post_complete_action.h, ut/s3_post_complete_action_test.cc
In multipart upload complete request, return failure if there is
no parts details in XML request string
=> EOS-14822: Bail out in case if XML string doesn't have parts details

auth/server/src/main/java/com/seagates3/acl/ACLValidation.java
[Splunk] fix for "s3tests.functional.test_s3.**test_bucket_acls_changes_persistent**"
Changes : Allowing ACL display name as "None" inorder to fix splunk test failures
=> EOS-14821: [Splunk] fix for allowing grantee displayname as None

server/s3_get_bucket_action.cc, server/s3_get_bucket_action_v2.cc, server/s3_object_list_v2_response.cc, server/s3_object_list_v2_response.h, ut/s3_get_bucket_action_v2_test.cc
Failed TCs are below:
s3tests.functional.test_s3.test_bucket_list_delimiter_prefix
s3tests.functional.test_s3.test_bucket_list_delimiter_prefix_underscore
These TCs are now passing. Locally (on my local VM) verified that existing UT and STs are running fine.
Note:
- QA needs to re-run third party solutions, e.g., veeam backup, and any other solution to make sure there is no regression, before merging to GA branch.
=> EOS-14826: [Splunk, ceph] Fix for Ceph S3 failed test cases in ListObject api

server/request_object.cc, server/request_object.h, server/s3_addb_map_auto.c, server/s3_addb_plugin_auto.cc, server/s3_addb_plugin_auto.h, server/s3_api_handler.h, server/s3_copy_object_action.cc, server/s3_copy_object_action.h, server/s3_object_api_handler.cc, ut/s3_object_api_handler_test.cc
CopyObject API skeleton implementation.
**CopyObject request to aws-s3** :
$ aws --endpoint-url https://s3.amazonaws.com --profile aws s3api copy-object --bucket dpg-bucket --copy-source archive-drone-pune-west/west-1745.jpg --key new-west-1745.jpg
{
"CopyObjectResult": {
"LastModified": "2020-11-05T04:09:25.000Z",
"ETag": "\"58870ec3982cbb2d691e8d0639f81c6a\""
}
}
**CopyObject request to cortx-s3** :
$ aws s3api copy-object --bucket my-bk --copy-source my-bk/one-kb-file --key new-1-kb-file
{
"CopyObjectResult": {
"LastModified": "", 
"ETag": ""
}
}
=> [LDR R1.1] Implement CopyObject API (skeleton only)

server/s3_auth_client.cc
Handle '!' case for invalid bucket name
=> [LDR-R1]: EOS-15028:s3:[splunk] fix for handling invalid bucket name

server/s3_motr_kvs_writer.cc
Sync flag was missing for put key val operation
=> EOS-15103: Add sync flag to put key val

st/clitests/awss3api_spec.py
Added some more STs to S3, covering object listing in a bucket, with regular and hierarchical object/key names.
=> EOS-15003: Add more STs to validate object listing in a bucket

server/s3_get_bucket_action_v2.cc, server/s3_object_list_response.cc, server/s3_object_list_response.h
During validation of List Object V2 request, S3 server is found to be not removing the URL encoded characters (e.g, %2F, %2B) from  'continuation-token'. The reason is unknown. Due to this, there was no removal of '%2F' and '%2B' characters from 'continuation-token', leading to further failure in base64 decoding of 'continuation-token', and thus, the object listing code enumerates from start key of the bucket, instead of from 'continuation-token'
- Added code to explicitly perform URL decoding of 'continuation-token'.
=> EOS-15332: S3 unable to URL decode 'continuation-token'.

server/request_object.cc, server/request_object.h, server/s3_addb_map_auto.c, server/s3_bucket_metadata.cc, server/s3_bucket_metadata.h, server/s3_bucket_metadata_v1.cc, server/s3_bucket_metadata_v1.h, server/s3_copy_object_action.cc, server/s3_copy_object_action.h, server/s3_error_codes.cc, server/s3_error_codes.h, server/s3_factory.h, server/s3_global_bucket_index_metadata.cc, server/s3_global_bucket_index_metadata.h, server/s3_object_action_base.cc, server/s3_object_metadata.cc, server/s3_object_metadata.h, ut/mock_s3_bucket_metadata.h, ut/mock_s3_factory.h, ut/mock_s3_request_object.h, ut/s3_copy_object_action_test.cc, ut/s3_delete_bucket_action_test.cc, ut/s3_delete_multiple_objects_action_test.cc, ut/s3_delete_object_action_test.cc, ut/s3_get_object_action_test.cc, ut/s3_global_bucket_index_metadata_test.cc, ut/s3_head_object_action_test.cc, ut/s3_object_action_base_test.cc, ut/s3_put_chunk_upload_object_action_test.cc, ut/s3_put_object_action_test.cc
**Test cases executed:**
1. Non-Existing destination bucket (Error thrown: NoSuchBucket)
2. Non-Existing source bucket (Error thrown: NoSuchBucket)
3. Non-Existing source object (Error thrown: NoSuchKey)
4. Source Object Size greater than 5GB (Error thrown: InvalidArgument)
5. Wrong input (No separator b/w buxket name and object name) to "x-amz-copy-source" header. (Error thrown: InvalidArgument)
6. Source and Destination same (Error thrown: InvalidRequest)
=> EOS:15088 - Load source metadata for CopyObject API

auth/server/src/main/java/com/seagates3/authentication/ClientRequestParser.java, auth/server/src/test/java/com/seagates3/authentication/ClientRequestParserTest.java, st/clitests/auth_spec_signcalc_test_data.yaml
fix Splunk failures for handling empty authorization header in Authserver request,
test case : 
s3tests.functional.test_headers.test_bucket_create_bad_authorization_empty
s3tests.functional.test_headers.test_object_create_bad_authorization_empty
**Old behavior** :
For Authorization request, if Auth server receives empty authorization header then we are returning "AuthorizationHeaderMalformed" response with 400 status code.
**New behavior** :
If aws receives empty authorization request then it will throw "Forbidden" response with 403 as status code
=>  [splunk fix] EOS-15368:s3: Update error code for empty authorization header

s3backgrounddelete/s3backgroundconsumer.service, s3backgrounddelete/s3backgrounddelete/cortx_s3_signal.py, s3backgrounddelete/s3backgrounddelete/object_recovery_processor.py, s3backgrounddelete/s3backgrounddelete/object_recovery_scheduler.py, s3backgrounddelete/s3backgroundproducer.service
_[EOS-15481](https://jts.seagate.com/browse/EOS-15481):_
_Change dynamic log level in s3 background delete_
1) s3 background service files need to accommodate reload command, when reload command is given (systemctl reload <service name>) it will send SIGUSR1signal to background process. s3 background process when receives this signal, need to read all modifiable parameters from its config file
2) Tried to use SIGHUP signal, but system daemon seems to handle this signal itself and reloads.It does not pass this signal to the registered handler.
_1) Change s3backgroundproducer config file to support reload option_
_2) Change object_recovery_scheduler.py to add signal handler for USR1_
_1) systemctl start s3backgroundproducer_
Ensure s3backgroundproducer service is up and running by checking …
=> EOS-15481: Dynamic log level changes

dev-starts3.sh, dev-stops3.sh, jenkins-build.sh, s3backgrounddelete/s3backgrounddelete/object_recovery_scheduler.py
_[EOS-14519](https://jts.seagate.com/browse/EOS-14519):_
_Handle deletions in dev environment using backgroundelete for delayed delete_
Handle deletions in dev environment using backgroundelete
whenever S3 IO is performed using jenkins build job or
any manually executed S3 IO (outside of the jenkins session) by manually running all services (e.g, s3server, s3auth, haroxy, ldap, motr) there should be no object leak in the dev environment
_1) Ensure that rabbit mq is installed and is up and running_
_2) Stop/Start s3background producer and consumer services_
_3) In case of cleanup mode or after tests are run, leave s3backgroundproducer and s3backgroundconsumer in a disabled state_
_1)./jenkins with STs should start and finish cleanly (no objects and index entries in motr, no background …
=> EOS-14519:Handle deletions in dev environment for delayed delete

rpms/s3/s3rpm.spec
Disabling strict check between s3 and motr rpm 
=> EOS-15439:S3: Disable motr version check from s3 rpm spec file

s3cortxutils/s3confstore/s3confstore/cortx_s3_confstore.py, s3cortxutils/s3confstore/setup.py
- [] **Code review:** _All discussions have been resolved_
- [] **Sanity Testing:** _jenkins job running at http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server-7.8.2003/315/ _
cat /etc/myconf.yaml
bridge: {manufacturer: homebridge.io, model: homebridge, name: Homebridge, pin: 031-45-154,
port: '51831', username: 'CC:22:3D:E3:CE:30'}
/usr/local/bin/s3confstore --getkey "bridge.port" --path "YAML:///etc/myconf.yaml"
51831
/usr/local/bin/s3confstore --setkey "bridge.port" --path "YAML:///etc/myconf.yaml" --setval 51840
/usr/local/bin/s3confstore --getkey "bridge.port" --path "YAML:///etc/myconf.yaml"
51840
cat /etc/myconf.yaml
bridge: {manufacturer: homebridge.io, model: homebridge, name: Homebridge, pin: 031-45-154,
port: '51840', username: 'CC:22:3D:E3:CE:30'}
cat …
=> EOS-15999:[MiniProvisioner] : s3confstore followup of EOS-15862 and implement set() and setkey() APIs

ansible/common_build_env.yml, scripts/env/dev/init.sh, scripts/env/release/init.sh, scripts/env/rpmbuild/init.sh
- moved the installation of cortx-py-utils from the ansible files to init.sh as there is no way we can differentiate the installation for opensource and for dev vm.
- handled the upgrade scenario for cortx-py-utils
jenkins job passed:
- http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server-7.8.2003/390/consoleFull
=> EOS-16307: Init.sh script should upgrade cortx-py-utils rpm to latest version

jenkins-build.sh
The help page in jenkins-build is now too long; I often need a quick and short list of supported options to copy from, and it is inconvenient to scroll up/down through the long help page.  So added this option for printing out a short list of options.
=> Add --short-help option in jenkins-build.sh

rpms/s3/buildrpm.sh, s3-sanity-test.sh, s3backgrounddelete/s3backgrounddelete/config/s3_background_delete_config.yaml.sample
In s3 rpm build script, the default debug log level in s3_background_delete_config.yaml is taken.
While building the RPM , this level needs to be changed to DEBUG for s3backgrounddelete if ENABLE_DEBUG_LOG is set
=> EOS:16252 Changed debug log level for s3backgrounddelete in build-rpm.sh

rebuildall.sh, runalltest.sh, s3cortxutils/s3confstore/s3confstore/cortx_s3_confstore.py, s3cortxutils/s3confstore/scripts/run_all_ut.sh, s3cortxutils/s3confstore/ut/s3confstore_unit_tests.py, scripts/env/dev/init.sh, scripts/env/release/init.sh, scripts/env/rpmbuild/init.sh
commit d457679cf58f716352cd90c3aaef5f182b06c3c4
Date:   Mon Jan 11 00:41:41 2021 -0700
EOS-16257: Build s3confstore and run UTs with jenkins build job
Added build step in rebuildall.sh script (just like s3recovery and s3backgrounddelete) for s3confstore.
Added UT for s3confstore and made sure they run as part of jenkins job via runalltest.sh
List of files:
modified:   rebuildall.sh
modified:   runalltest.sh
new file:   s3cortxutils/s3confstore/scripts/run_all_ut.sh
new file:   s3cortxutils/s3confstore/ut/s3confstore_unit_tests.py
Testing:
UT:
1. using rebuildall.sh, using console logs, verified s3confstore is being compiled.
2. using ./jenkins-build.sh and ./runalltest.sh, verified s3confstore_unit_tests.py is …
=> EOS-16257: Build s3confstore and run UTs with jenkins build job

scripts/coverage/run_all_coverage.sh
Commit-id option is not required to pass to code coverage script as "bash <(curl -Ls $codacy_coverage_url) report" uses latest commit id to upload the coverage report unless we need to explicitly upload against a specific commit-id. But if not then it is not required to pass.At present we are using latest commit-ids with default branch as main to upload the reports.
=> Remove commit-id option from code coverage upload

rpms/s3/buildrpm.sh
While fixing https://jts.seagate.com/browse/EOS-16252, the build broke because of the missing '/' in the buildrpm.sh 
11:16:35  + sed -i 's/#logLevel=DEBUG.*$/logLevel=DEBUG/g' cortx-s3server-1.0.0-giteb492032/auth/resources/authserver.properties.sample
11:16:35  + sed -i 's/S3_LOG_MODE:.*$/S3_LOG_MODE: DEBUG/g' cortx-s3server-1.0.0-giteb492032/s3config.release.yaml.sample
11:16:35  + sed -i 's/file_log_level:.*$/file_log_level: 10/g' cortx-s3server-1.0.0-giteb492032s3backgrounddelete/s3backgrounddelete/config/s3_background_delete_config.yaml.sample
11:16:35  sed: can't read cortx-s3server-1.0.0-giteb492032s3backgrounddelete/s3backgrounddelete/config/s3_background_delete_config.yaml.sample: No such file or directory
[Pipeline] }
=> EOS-16752: Broken Main Branch -Fixed '/' typo in s3 buildrpm.sh

ansible/files/yum.repos.d/centos7.8.2003/cortx_py_utils.repo, scripts/env/dev/init.sh, scripts/env/release/init.sh, scripts/env/rpmbuild/init.sh
Jenkins job:  
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server-7.8.2003/482/
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server-7.8.2003/483/
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server-7.8.2003/484/
Jenkins job log:
`cortx-py-utils-1.0.0-99_23eb199.noarch
18:10:46  Loaded plugins: fastestmirror, priorities, product-id, search-disabled-repos,
18:10:46                : subscription-manager
18:10:47  Resolving Dependencies
18:10:47  --> Running transaction check
18:10:47  ---> Package cortx-py-utils.noarch 0:1.0.0-99_23eb199 will be erased
18:10:49  --> Finished Dependency Resolution
18:10:49  
18:10:49  Dependencies Resolved
18:10:49  
18:10:49  ================================================================================ …
=> EOS-17079:S3: cortx-py-utils algorithm changed from upgrade to remove and install

ansible/files/yum.repos.d/centos7.8.2003/cortx_py_utils.repo, scripts/env/dev/init.sh, scripts/env/release/init.sh, scripts/env/rpmbuild/init.sh, scripts/kafka/install-kafka.sh
- changed cortx-py-utils path from stable to main
- hard-coded the confluent-kafka version to 1.5.0
- changed location of confluent-kafka installation from init.sh to kafka-install.py
- kafka download url was changed to correct location
=> EOS-16667:S3: Changes required for main to pass pre-merge and mini-provisioner changes

scripts/haproxy/s3haproxyconfig/s3haproxyconfig/s3_haproxy_config.py
Added fix to uncomment out the ssl crt statement.
File modified :
scripts/haproxy/s3haproxyconfig/s3haproxyconfig/s3_haproxy_config.py
=> EOS-16872 : Configure HAProxy as a part of S3 setup 3 Node VM component provisioning

s3cortxutils/s3confstore/s3confstore/cortx_s3_confstore.py, s3cortxutils/s3confstore/ut/s3confstore_unit_tests.py
**### Issue**
Cortx-Utils had support for get_keys() which lists all the key-value pairs in a file.
Hooked up the support in s3confstore for get_keys API
[root@ssc-vm-c-1632 cortx-s3server]# s3confstore yaml:///opt/seagate/cortx/s3/s3backgrounddelete/config.yaml getallkeys
['version_config>version', 'cortx_s3>endpoint', 'cortx_s3>service', 'cortx_s3>default_region', 'cortx_s3>daemon_mode', 'cortx_s3>s3_instance_count', 'cortx_s3>messaging_platform', 'message_bus>topic', 'message_bus>consumer_group', 'message_bus>consumer_id_prefix', 'message_bus>producer_id', 'message_bus>producer_delivery_mechanism', 'message_bus>consumer_sleep', 'logconfig>scheduler_logger_name', 'logconfig>processor_logger_name', 'logconfig>logger_directory', 'logconfig>scheduler_log_file', …
=> EOS-16890:Support for get_all_keys in S3confstore

auth-utils/jclient/pom.xml, auth-utils/jclient/src/main/java/com/seagates3/javaclient/JavaClient.java
log4j package is moved to log4j-core
hence updating log4j version in jclient code.
Link : https://mvnrepository.com/artifact/log4j/log4j
JIRA : https://jts.seagate.com/browse/EOS-17536
=> EOS-17536:JClient: Upgrade log4j version 1.2.17 -> 2.14.0 (log4j-core)

docs/CORTX-S3 Server Quick Start Guide.md
The s3 specific SUPPORT.md page -> https://github.com/Seagate/cortx-s3server/blob/main/SUPPORT.md needs updating. 
I think it's better to just point to the main general support.md page in the main CORTX repo and keep it updated in one place and so I've made changes to point there for support.
Signed-off-by: Justin Woo <justin.woo@seagate.com>
-----
[View rendered docs/CORTX-S3 Server Quick Start Guide.md](https://github.com/Seagate/cortx-s3server/blob/justinzw-patch-1/docs/CORTX-S3 Server Quick Start Guide.md)
=> Update CORTX-S3 Server Quick Start Guide.md

scripts/ldap/setup_ldap.sh, scripts/provisioning/s3_setup
commit 6f6e6cfa2019ea1753a747a4470ec28253779c44
Date:   Fri Feb 12 01:26:46 2021 -0700
EOS-17389: LR R2: Mini Provisioner - Convert s3_setup to python - config phase <patch 1: changes in setup_ldap.sh>
As described in ticket EOS-17389 for setup_ldap.sh and in caller in s3_setup
Added/modified/deleted files:
modified:   scripts/ldap/setup_ldap.sh
modified:   scripts/provisioning/s3_setup
Unit test:
Run "s3_setup config" with these changes and verified steps worked. Performed complete mini-provisioner s3 steps
Signed-off-by: pratyush-seagate <pratyush.k.khan@seagate.com>
=> EOS-17389: LR R2: Mini Provisioner - Convert s3_setup to python - config phase <patch 1: changes in setup_ldap.sh>

scripts/s3-support-bundles/s3_bundle_generate.sh
S3 support bundle uses /tmp directory for storing processed data of s3server.
As per latest discussion we are planning to do below changes in s3 support bundle,
Old path : /tmp/s3_support_bundle_pid-value
New Path : (interface-path-provided-by-csm)/s3/s3_support_bundle_(pid-value)
JIRA : https://jts.seagate.com/browse/EOS-17612
=> [Cortx-1.0]:EOS-17612 : s3 support bundle change

scripts/s3-support-bundles/s3_bundle_generate.sh
S3 support bundle uses /tmp directory for storing processed data of s3server.
As per latest discussion we are planning to do below changes in s3 support bundle,
Old path : /tmp/s3_support_bundle_pid-value
New Path : (interface-path-provided-by-csm)/s3/s3_support_bundle_(pid-value)
JIRA : https://jts.seagate.com/browse/EOS-17612
Mini-provisioning : http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Mini-Provisioning/job/cortx-s3server/291/console
=> EOS-17612: S3: Support bundle temporary directory path change

docs/CORTX-S3 Server Quick Start Guide.md
Signed-off-by: Patrick Hession <patrick.hession@seagate.com>
-----
Added a line to enable the EPEL repo before installing python-pip with yum.
[View rendered docs/CORTX-S3 Server Quick Start Guide.md](https://github.com/Seagate/cortx-s3server/blob/hessio-patch-1/docs/CORTX-S3 Server Quick Start Guide.md)
=> Enable the EPEL repo before installing pip

installhelper.sh, rpms/s3/s3rpm.spec, scripts/haproxy/s3haproxyconfig/s3haproxyconfig/s3_haproxy_config.py, scripts/provisioning/_s3_setup, scripts/provisioning/cleanupcmd.py, scripts/provisioning/configcmd.py, scripts/provisioning/initcmd.py, scripts/provisioning/postinstallcmd.py, scripts/provisioning/resetcmd.py, scripts/provisioning/s3_prov_config.yaml, scripts/provisioning/s3_setup, scripts/provisioning/s3setup_prereqs.json, scripts/provisioning/setupcmd.py, scripts/provisioning/testcmd.py
We need to replace present 's3_setup', which is a shell based script, with a python based script.
As of now keeping the new python provisioning script name as '_s3_setup', but its name will
be replaces as soon as we EOL the shell script with same name.
=> EOS:16437 - Add new python provisioning script '_s3_setup' with 'post_install' and 'cleanup'

server/s3_object_metadata.h, ut/s3_object_metadata_test.cc
Added following unit test cases 
FRIEND_TEST(S3ObjectExtendedMetadataTest, ConstructorTest);
FRIEND_TEST(S3ObjectExtendedMetadataTest, AddExtendedEntrySingleFragmentWithoutPartTest);
FRIEND_TEST(S3ObjectExtendedMetadataTest, AddExtendedEntryMultiFragmentWithoutPartTest);
FRIEND_TEST(S3ObjectExtendedMetadataTest, AddExtendedEntrySingleFragmentSinglePartTest);
FRIEND_TEST(S3ObjectExtendedMetadataTest, AddExtendedEntryMultiFragmentSinglePartTest);
FRIEND_TEST(S3ObjectExtendedMetadataTest, AddExtendedEntrySingleFragmentMultiPartTest);
FRIEND_TEST(S3ObjectExtendedMetadataTest, AddExtendedEntryMultiFragmentMultiPartTest);
Following are result of test cases 
[root@ssc-vm-1825 cortx-s3server]# ./bazel-bin/s3ut --gtest_filter=S3ObjectExtendedMetadataTest.* …
=> EOS-17404 - S3faulttolerence - UT for S3 object metadata changes

rpms/s3/s3rpm.spec
s3_setup script needs python36-ldap package to do openldap configuration and cleanup.
=> EOS:18227 - Add python36-ldap package as requirment in s3rpm spec file.

auth/resources/authserver.properties.sample, auth/server/src/main/java/com/seagates3/authserver/AuthServerConfig.java, auth/server/src/test/java/com/seagates3/authserver/AuthServerConfigTest.java, rebuildall.sh, scripts/enc_ldap_passwd_in_cfg.sh
Remove JKS and use confstore to store openldap password
=> EOS-17358: Auth : Removal of JKSstore from Authserver

s3config-test.yaml, s3config.release.yaml.sample, s3config.yaml.sample, server/s3_get_object_action.cc, server/s3_option.cc, server/s3_option.h
In POC EOS-16558 we confirmed that reducing size of first read helps achieve better TTFB. 
This PR is to finalize the changes and deliver it to main
=> S3: Finalize and deliver fix for small "first read"

s3config-test.yaml, s3config.release.yaml.sample, s3config.yaml.sample, server/s3_common.h, server/s3_factory.h, server/s3_motr_writer.cc, server/s3_motr_writer.h, server/s3_object_action_base.cc, server/s3_object_metadata.cc, server/s3_object_metadata.h, server/s3_option.cc, server/s3_option.h, server/s3_post_multipartobject_action.cc, server/s3_post_multipartobject_action.h, server/s3_put_object_action.cc, server/s3_put_object_action.h, ut/s3_object_metadata_test.cc, ut/s3_put_object_action_test.cc
- Code changes in PUT api (scenario: simple new object; no object overwrite) to support S3 fault mode
- Disabled UT that are failing due to changes (which will be enabled or removed later while fixing ST/UT)
=> S3faulttolerence - Put Object (Simple) API support - Part1

scripts/provisioning/cleanupcmd.py
Below are the config files which will be **reverted** in **Cleanup phase**
auth_config="/opt/seagate/cortx/auth/resources/authserver.properties"
auth_keystore_config="/opt/seagate/cortx/auth/resources/keystore.properties"
auth_jksstore="/opt/seagate/cortx/auth/resources/s3authserver.jks"
auth_jksstore_template="/opt/seagate/cortx/auth/scripts/s3authserver.jks_template"
s3_config="/opt/seagate/cortx/s3/conf/s3config.yaml"
s3_bgdelete_config="/opt/seagate/cortx/s3/s3backgrounddelete/config.yaml"
=> [mini-provisioning:cleanup]EOS-18718:Revert config files

server/s3_copy_object_action.cc, server/s3_post_multipartobject_action.cc, server/s3_put_chunk_upload_object_action.cc, server/s3_put_object_action.cc
EOS-18618 - Fix memory leaks from evhttp_uridecode and replace deprecated evhttp_decode_uri
Files modified :
server/s3_copy_object_action.cc
server/s3_post_multipartobject_action.cc
server/s3_put_chunk_upload_object_action.cc
server/s3_put_object_action.cc
Testing :
On CLI :
`put-object pbucket1/object - result(PASS)`
`copy-object pbucket1/object - result(PASS)`
End result : put-object and copy-object via CLI is successful for regular objects.
=> EOS-18618 - Fix memory leaks from evhttp_uridecode and replace deprecated evhttp_decode_uri

scripts/install_prereqs.sh, scripts/provisioning/cleanupcmd.py
commit 1411b841026c952afae2149108b8da2c5a645ef3
Date:   Tue Mar 16 01:42:30 2021 -0600
EOS-17952: Mini Provisioner: s3_setup Cleanup phase
Cleanup ldap config and schemas created by setup_ldap.sh during config phase
Add hooks for step 1 and 3 as mentioned in EOS-17952 (TODO: implement the stub hooks and integrate with this code by respective developers)
openldap related external cleanup code is removed from install_prereqs.sh
Added/modified/deleted files:
modified:   scripts/provisioning/cleanupcmd.py
modified:   scripts/install_prereqs.sh
Test:
With the changes, single node mini-provisioner deployed on VM and tested multiple times using loop with cleanup.
"post-install, config, init and cleanup" loop is verified …
=> EOS-17952: Mini Provisioner: s3_setup Cleanup phase

scripts/env/dev/init.sh, scripts/env/release/init.sh, scripts/env/rpmbuild/init.sh
Root cause : configobj package installation is missing in case of opensource ansible script, hence ST are breaking if someone use opensource setup. (i.e. running ansible script with "-a" option)
Fix : pip3 install configobj
I have tested the patch locally on this setup and tests were successful.
=> GitIssue-759:s3:St failure fix, pkg configobj was not installed

scripts/install_prereqs.sh, scripts/provisioning/_s3_setup, scripts/provisioning/cleanupcmd.py, scripts/provisioning/configcmd.py, scripts/provisioning/initcmd.py, scripts/provisioning/postinstallcmd.py, scripts/provisioning/preparecmd.py, scripts/provisioning/resetcmd.py, scripts/provisioning/s3setup_prereqs.json, scripts/provisioning/setupcmd.py, scripts/provisioning/testcmd.py
commit 206feafa23c23fc0cc65c860c1c4f577b1e9af9c
Date:   Mon Mar 22 03:23:33 2021 -0600
EOS-18823: Mini Provisioner: Restructure s3setup_prereqs.json by separating prerequistes sections for each phase
Restructure s3setup_prereqs.json for each phase as described in the ticket's DoD and assocaited code changes in the respective phases and in setupc
Added/modified/deleted files:
modified:   scripts/install_prereqs.sh
modified:   scripts/provisioning/_s3_setup
modified:   scripts/provisioning/cleanupcmd.py
modified:   scripts/provisioning/configcmd.py
modified:   scripts/provisioning/initcmd.py
modified:   scripts/provisioning/postinstallcmd.py
modified:   scripts/provisioning/preparecmd.py
modified: …
=> EOS-18823: Mini Provisioner: Restructure s3setup_prereqs.json by separating prerequistes sections for each phase

s3backgrounddelete/s3backgrounddelete/config/s3_background_delete_config.yaml.sample, s3backgrounddelete/s3backgrounddelete/cortx_s3_config.py, s3backgrounddelete/s3backgrounddelete/cortx_s3_constants.py, s3backgrounddelete/s3backgrounddelete/object_recovery_msgbus.py, s3cortxutils/s3msgbus/s3msgbus/cortx_s3_msgbus.py, scripts/provisioning/cleanupcmd.py, scripts/provisioning/configcmd.py, scripts/provisioning/resetcmd.py, st/clitests/s3_background_delete_config_test.yaml
Implemented following things
- Topic create - config phase
- Purge - 'reset phase'
- topic delete - 'cleanup phase'
Unit testing result:
[root@ssc-vm-2859 cortx-s3server]# /opt/seagate/cortx/s3/bin/s3_setup config --config "yaml:///opt/seagate/cortx/s3/conf/s3.config.tmpl.1-node"
INFO: Creating random jks password for Auth server..
Generating password for jks keystore used in authserver...
Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore /opt/seagate/cortx/auth/resources/s3authserver.jks -destkeystore /opt/seagate/cortx/auth/resources/s3authserver.jks -deststoretype pkcs12".
Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 …
=> EOS-17270: [MsgBus] Add create/delete topic in the s3 provisoner

auth/resources/authserver.properties.sample, auth/resources/keystore.properties.sample, scripts/create_auth_jks_password.sh, scripts/enc_ldap_passwd_in_cfg.sh
s3cipher constant key needs to be updated in authserver.
1) const_ldap_key is still ued as "openldap" but it should be "cortx"
2) keystore.properties has old s3cipher command 
=> [Bug] EOS-19132:Auth: change constant key for s3cipher in authserver

server/s3_get_multipart_bucket_action.cc, server/s3_object_list_response.cc, server/s3_object_list_response.h, ut/s3_object_list_response_test.cc
Multipart listing to not disply uploadid which gets in as key
in the multipart table, listing to show same objects with diffferent
upload ids in case of simultaneous multipart upload of same object
=> [EOS-17282]Multipart listing changes as per new design

scripts/ldap/ldapaccountaction.py, scripts/provisioning/resetcmd.py, scripts/provisioning/setupcmd.py
Delete data directories e.g. ou=accesskeys, ou=accounts,ou=idp from dc=seagate,dc=com tree"
=> [Draft] EOS-18890:[s3-mini-provisioner:reset phase]: Delete ldap records

server/s3_addb_map_auto.c, server/s3_object_metadata.cc, server/s3_object_metadata.h, server/s3_post_multipartobject_action.cc, server/s3_post_multipartobject_action.h, ut/s3_post_multipartobject_action_test.cc
After re-basing 'br/DG/EOS-19183' with 'main' (locally in my dev workspace), all STs have passed.
So, this change is ready to be merged in 'FaultTolerence' branch.
Note: 'FaultTolerence' branch has to be re-based with 'main' in a separate commit.
=> EOS-19183: Remove multipart re-design changes from FaultTolerence branch

server/s3_put_object_action.cc, server/s3_put_object_action.h
- Fixed the object/fragment size calulcation issue.
=> EOS-19196: Wrong size of the primary object during S3 fault

scripts/provisioning/templates/s3.reset.tmpl.1-node, scripts/provisioning/templates/s3.reset.tmpl.1-node.sample
=> EOS-19428: 's3_setup reset' fails in miniprovisioner setup.

scripts/provisioning/configcmd.py
In single node deployment , we saw issue where server node count is not handled properly ..
hence added this logic to fix this issue .
verified on single node deployment by manually updating the config file.
=> [EOS-19517] Handling storage set count parsing on server node list

rpms/s3test/s3test.spec, scripts/provisioning/s3setup_prereqs.json, scripts/provisioning/testcmd.py, scripts/s3-sanity/s3-sanity-test.sh
_[EOS-19178](https://jts.seagate.com/browse/EOS-19178):_
_Integrate S3TestRpm with Miniprovisioning Job such that sanity is successfully executed._
1. Removed dependency on cortx-s3server of cortx-s3-test rpm.
2. Removed unnecessary rpms from prerequisites json for test phase.
3. ldapsearch in sanity script now needs an endpoint parameter, so that it can work from another machine.
4. Removed return statement from testcmd.py file, and now it invokes sanity script.
**Miniprovisioning job should install cortx-s3-test rpm, set appropriate parameter in template file and invoke s3_setup.
s3_setup inturn invokes sanity script. Sanity script should return success.**
<details>
<summary>Output of Case 1</summary>
[Full Log](http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Mini-Provisioning …
=> [EOS-19178] S3Test rpm integration with CI-CD Miniprovisioning Job

auth/resources/keystore.properties.sample
kesytore.properties does not required logger config which was causing conflicts for "logLevel" properteis with authserver.properties 
hence debug mode value was updated as INFO while loading authserver 
=> EOS-19564:Auth:Fix for Authserver LogLevel values

server/s3_get_bucket_action.cc, server/s3_object_action_base.cc, server/s3_object_metadata.cc, server/s3_object_metadata.h, server/s3_put_object_action.cc, st/clitests/fault_tolerence_spec.py, st/clitests/s3kvs.py
- Removed prefix delimiter '~' from extended/fragmented entry key names
- Extended metadata goes in extended metadata index.
- Updated fault tolerance spec file
=> EOS-19192: Extended metadata added to different index table

scripts/ldap/replication/setupReplicationScript.sh, scripts/provisioning/setupcmd.py
New handler has been added with initial check for handling
None-type or Empty strings. This would be further enhanced.
Files modified:
scripts/provisioning/setupcmd.py
Testing :
`UT with no value and empty value keys in argument file is throwing error as expected.`
=> EOS-19622 : s3_setup needs to verify values of keys in argument file.

server/s3_iem.h, server/s3_log.cc, server/s3_log.h
- removed ASPRINTF! and unneeded allocations for EVERY! log write!!!
- uses tls-approach.
- change the semantics of s3_iem() so that it becomes similar to s3 log.
- use templated verbosity select method to be able to handle const-expressions inside s3_log macro
- example: s3_log(cond ? S3_LOG_DEBUG : S3_LOG_ERROR, ...).
=> github833: S3 logger robustness, performance improvement and reorg proposal

resources/s3_error_messages.json, server/request_object.cc, server/s3_put_chunk_upload_object_action.cc, server/s3_put_multiobject_action.cc, server/s3_put_multiobject_action.h, server/s3_put_object_action.cc, ut/s3_put_multiobject_action_test.cc, ut/s3_put_object_action_test.cc
_[EOS-19636](https://jts.seagate.com/browse/EOS-19636):_
_Uploading object with 2KB metadata size fails_
root cause: 
S3 server adds identifier "x-amz-meta-" in to metatadata key in to header. When the metadata length gets calculated it was also considering the above additional length which was causing the upload object fail. 
Fix:
Subtracted the length of  "x-amz-meta-" from the metadata length.
Corrected the error message for the header or metadata exceed.   
Performed the object upload with metadata as 2048 on dev VM. Object uploaded successfully.
Performed the object upload with metadata as 2049 on dev VM. Object upload failed with proper error message.
<details>
<summary>Output of UT</summary>
[root@ssc-vm-3160 cortx-s3server]# aws s3 cp LICENSE s3://mp-bkt-test1619002304 …
=> EOS-19636:  Uploading object with 2KB metadata size fails

auth/server/src/main/java/com/seagates3/authserver/AuthServer.java, auth/server/src/main/java/com/seagates3/controller/AccountController.java, auth/server/src/main/java/com/seagates3/controller/UserController.java, auth/server/src/main/java/com/seagates3/dao/AccountDAO.java, auth/server/src/main/java/com/seagates3/dao/UserDAO.java, auth/server/src/main/java/com/seagates3/dao/ldap/AccountImpl.java, auth/server/src/main/java/com/seagates3/dao/ldap/UserImpl.java, auth/server/src/test/java/com/seagates3/controller/AccountControllerTest.java, auth/server/src/test/java/com/seagates3/controller/UserControllerTest.java
1) In Authserver.properties file LdapSearchResultsSizeLimit value must be greater than or equals to maxAccountLimit & maxIAMUserLimit value 
2) for getTotalCount() api, use listall() method from DAO layer instead of calling from ldapUtils.java
=> EOS-19572:Auth: account/iamuser creation limit config fixes

ansible/openldap.yml
In case of dev vm we have max ldap search limit set as default value ie.e. 500 
hence if we have entries more than 500 then create/list API will be broken with "Size Limit Exceeded" error thrown by ldap.
In case of provisioned setup:
This case is already handled in setup_ldap.sh script hence no changes required in case of prod setup script.
=> EOS-19814:Auth: increase LdapResult size from 500 -> 10000 for dev vm

server/request_object.cc, server/request_object.h, server/s3_evbuffer_wrapper.cc, server/s3_evbuffer_wrapper.h, server/s3_get_object_action.cc, server/s3_get_object_action.h, server/s3_motr_context.h, server/s3_motr_reader.cc, server/s3_motr_reader.h, server/s3_motr_writer.h, ut/s3_get_object_action_test.cc
evbuffer_add() being used during read operation, copied data
o libevent buffers, mechanism to avoid data copy,
populate data directly form motr and send those buffers
to libevent, use 16k buffers even for read operations
=> EOS-19530: Avoidance of memcpy during read

jenkins-build.sh
In case of dev vm we are observing the environment variable PATH which does not has "/usr/local/bin" entry hence python modules in s3server like s3iamcli, s3confstore, s3cipher seems to be broken.
=> EOS-20265:add missing path in PATH variable

s3backgrounddelete/s3backgrounddelete/object_recovery_validator.py, server/s3_probable_delete_record.cc, server/s3_probable_delete_record.h, server/s3_put_object_action.cc, server/s3_put_object_action.h
Object leak scenarios:
1. When nth extended object creation fails
2. When saving to meta data fails and S3 cleanup fails
=> EOS-19181: Implementation of BD changes for S3 fault tolerenace feature

server/s3_log.h
Problem:
Due to the logic of glog, it's needed to call LOG() << ... exactly from
the code in specific file to see proper file names in the log.
Solution:
Remove templated switch, return macro switch back.
Note:
Will not support s3_log(cond ? option1 : option2, ...) expression.
=> [EOS-20607] S3 logger: Return macro based log severity switch to address

s3config-test.yaml, s3config.release.yaml.sample, s3config.yaml.sample, server/s3_motr_writer.cc
_[EOS-20328](https://jts.seagate.com/browse/EOS-20328):_
_Tuning the read mempool to reduce memory consumption._
1. Removed array of buffers and kept a single 16k buffer size
2. Plugged 16k to write buffer where it is using from read mempool.
Ran ST's to check the impact of changes on system.
MP Job : http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Mini-Provisioning/job/cortx-s3server/1073/console
Pre-Merge Job : http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Component-Test/job/S3Server-PreMerge-Test/1087/console
Parallelly uploaded 2 100 mb files to s3 server to check if there is any issue. 
=> [EOS-20328] Tuning of mempool to avoid read mempool buffers

auth-utils/s3iamcli/s3iamcli/account.py
Fix error message output for delete account in case of s3iamcli commands.
e.g
[root@ssc-vm-2496 ~]# s3iamcli DeleteAccount --access_key AKIAWuGrR44RRmqeBKwJ_rbzRA --secret_key YoIRQ2HjdlzWdpqE3d5IXkk6BPJT3B0RW2BaUAdI
Account name is required.
**local variable 'message' referenced before assignment**
[root@ssc-vm-2496 ~]#
=> [EOS-20794] s3iamcli: Delete Account error message fix

server/s3_addb_map_auto.c, server/s3_get_bucket_action.cc, server/s3_object_metadata.cc, server/s3_object_metadata.h, server/s3_put_multiobject_action.cc
- Changed the parsing logic
- Also, removed code that relates to "~" as start object prefix used in earlier design of
S3 fault tolerance feature.
=> [EOS-19670] Parsing of extended metadata key, since object name can contain delimiter |

scripts/env/dev/init.sh, scripts/env/release/init.sh, scripts/env/rpmbuild/init.sh, scripts/kafka/install-kafka.sh, scripts/s3-support-bundles/s3_bundle_generate.sh, st/clitests/backgrounddelete_spec.py, st/clitests/s3fi.py
Fixed grep command in support bundle.
`[root@ssc-vm-2383 s3]# cd /opt/seagate/cortx/auth/resources/
[root@ssc-vm-2383 resources]#  authserver_logdir=`cat ./authserver.properties | grep "logFilePath=" | cut -f2 -d'=' | sed -e 's/^[ \t]*//' -e 's/#.*//' -e 's/^[ \t]*"\(.*\)"[ \t]*$/\1/'`
[root@ssc-vm-2383 resources]#
[root@ssc-vm-2383 resources]# echo $authserver_logdir
[root@ssc-vm-2383 resources]#
[root@ssc-vm-2383 resources]# below is valid command
[root@ssc-vm-2383 resources]#
[root@ssc-vm-2383 resources]#  authserver_logdir=`cat ./authserver.properties | grep "logFilePath" | cut -f2 -d'=' | sed -e 's/^[ \t]*//' -e 's/#.*//' -e 's/^[ \t]*"\(.*\)"[ \t]*$/\1/'`
[root@ssc-vm-2383 resources]# echo $authserver_logdir
/var/log/seagate/auth/server
[root@ssc-vm-2383 resources]#`
Also handled …
=> [Bug] EOS-20866: s3: support bundle fix for handling grep command

server/s3_object_data_copier.cc, server/s3_object_data_copier.h, ut/s3_object_data_copier_test.cc
- Code changes to trim buffer after the source object size(during copy operation)
Note: MD5 checksum of downloaded object is still not matching with the original source object, and investigation for the same is in progress.
=> EOS-20605: CopyObject regression

s3config-test.yaml, s3config.release.yaml.sample, s3config.yaml.sample, server/s3_evbuffer_wrapper.cc, server/s3_md5_hash.h, server/s3_motr_context.cc, server/s3_motr_context.h, server/s3_motr_reader.cc, server/s3_motr_reader.h, server/s3_motr_writer.cc, server/s3_option.cc, server/s3_option.h
_[EOS-20643](https://jts.seagate.com/browse/EOS-20643):_
_[EOS-19705](https://jts.seagate.com/browse/EOS-19705):_
_Code for Getting and Verifying Checksums stored in Motr._
1. Allocate attr structure based on protection info to be used.
2. Make read call, motr should populate attr structure with relevant data.
3. On Read success, calculate pi of the data returned and compare it with the stored.
4. Fail Read Operation if above step fails.
Currently this implementation is only Code Complete. Code can be compiled with the relevant motr commit id, but UT's and ST's are failing.
=> [EOS-20643]  Getting and Verifying Checksums stored in Motr

scripts/ldap/ldapaccountaction.py, scripts/provisioning/configcmd.py, scripts/provisioning/s3_haproxy_config.py, scripts/provisioning/s3_setup, scripts/provisioning/setupcmd.py
1. Renamed hosts_list_file.txt to ldap_hosts_list_file.txt
2. Logged the o/p of ldap_hosts_list_file.txt to logger
3. Moved the ldap_hosts_list_file.txt to /opt/seagate/cortx/s3/tmp
UT:
Verified on custom S3 deployment job 
http://eos-jenkins.colo.seagate.com/job/Cortx-Deployment/job/Mini-Provisioner/job/S3-Deploy/252/console
=> EOS-19643: Handling and logging of temporary file hosts_list_file.txt

README.md
Removed Codacy CLI Analysis Badge as it is outdated.
-----
[View rendered README.md](https://github.com/Saumya-Sunder/cortx-s3server-1/blob/patch-10/README.md)
=> Removed Codacy CLI Analysis Badge

scripts/provisioning/initcmd.py, scripts/provisioning/resetcmd.py
_[EOS-21106](https://jts.seagate.com/browse/EOS-21106):_
_Handled already exist case for the background delete account_
Handled already exist case for the background delete account for init and reset phase
=> EOS-21106: Handled already exist case for the background delete account

server/s3_post_complete_action.cc, st/clitests/awss3api_spec.py, ut/s3_post_complete_action_test.cc
Solution:
- Changed the implementation of Multipart complete API to not abort the multipart operation when object size
is too small (<5MB) or too large (>5GB).
Note: Verified the change using test mentioned in Jira.
=> EOS-20998: List multipart returns empty, after unsuccessful complete multipart

auth/server/pom.xml
Update netty package version,
**From** : 4.1.42.Final
**To** : 4.1.63.Final
maven repo : https://mvnrepository.com/artifact/io.netty/netty-all
Tried using latest 4.1.65.Final version of netty but that seems to be failing while doing signature calculation which uses FullHttpRequest object (isuss is FullHttpRequest has empty content  field which causes Signature mismatch in our case)
hence using 4.1.63.Final version for upgrade .
=> EOS-19860: Auth: netty jar upgrade 4.1.42.Final -> 4.1.63.Final

scripts/env/common/configure_lnet.sh
Tested below scenarios , working fine .
Case 1: When lustre rpm is not present in VM.
[root@cortxhost common]# ./configure_lnet.sh
package kmod-lustre-client is not installed
[root@cortxhost common]#
Case 2: When lustre rpm is present and Lnet is not configured in VM.
[root@cortxhost common]# ./configure_lnet.sh
kmod-lustre-client-2.12.5-99.el7.x86_64
Lnet is down.
configuring lnet
Redirecting to /bin/systemctl restart lnet.service
Redirecting to /bin/systemctl restart lnet.service
Lnet is up and running
[root@cortxhost common]# lctl list_nids
10.230.241.171@tcp
[root@cortxhost common]#
Case 3: When lustre rpm is present and Lnet is pre-configured in VM.
[root@cortxhost common]# ./configure_lnet.sh
kmod-lustre-client-2.12.5-99.el7.x86_64
Lnet is up and running
[root@cortxhost common]# …
=> EOS-21167 :Add validation of lustre rpm before reconfiguring lnet during execution of init.sh

server/s3_bucket_metadata.h, server/s3_get_object_action.cc, server/s3_get_object_action.h, server/s3_object_action_base.cc, server/s3_object_action_base.h, server/s3_object_metadata.cc, server/s3_object_metadata.h, server/s3_part_metadata.cc, server/s3_part_metadata.h, server/s3_post_complete_action.cc, server/s3_post_complete_action.h, server/s3_post_multipartobject_action.cc, server/s3_post_multipartobject_action.h, server/s3_probable_delete_record.cc, server/s3_probable_delete_record.h, server/s3_put_multiobject_action.cc, ut/mock_s3_bucket_metadata.h, ut/mock_s3_factory.h, ut/mock_s3_object_extended_metadata.h, ut/mock_s3_object_metadata.h, ut/mock_s3_part_metadata.h, ut/s3_copy_object_action_test.cc, ut/s3_delete_bucket_action_test.cc, ut/s3_post_complete_action_test.cc, ut/s3_put_object_action_test.cc
This change also has other fixes e.g.:
1. Get Object api changes to read several objects created as part of multipart redesign.
These code change are ported from FaultTolerance branch, with some changes.
2. Changes in implementation files related to Multipart functionality, other than Complete multipart API file
=> EOS-17572: S3 Multipart Post Complete api implementation (Multipart re-design)

server/s3_get_object_action.cc, server/s3server.cc
request id may be stale, which is invalid
read in logging
=> [EOS-21924] Fix for invalid reads as reported in valgrind

auth-utils/jclient/src/main/java/com/seagates3/javaclient/ClientConfig.java, st/clitests/jcloud_spec.py
When STs are run with valgrind, jcloud and jclient tests fails
due to timeout, runing with valgrind results in more time
for request processing
=> EOS-22090: System tests fails with timeout when run with valgrind

s3cortxutils/s3confstore/s3confstore/cortx_s3_confstore.py, scripts/provisioning/setupcmd.py, scripts/swupdate/merge.py
_[EOS-21416](https://jts.seagate.com/browse/EOS-21416):_
_Removed workaround used for iterating all keys using get_all_keys()_
- Removed the workaround from get_all_keys()
=> EOS-21416: Removed workaround used for iterating all keys using get_all_keys()

rpms/s3/s3rpm.spec
Use bazel 4.1.0 explicitly so that it gets installed/updated even if an older version is already installed. 
Test log 
```
00:01:42.506  + yum-builddep -y /tmp/workspace/GitHub-custom-ci-builds/centos-7.8/s3-custom-build/rpms/s3/s3rpm.spec
00:01:42.506  Loaded plugins: fastestmirror, ovl, priorities
00:01:42.764  Enabling base-source repository
00:01:42.764  Enabling extras-source repository
00:01:42.764  Loading mirror speeds from cached hostfile
00:01:45.294  Loading mirror speeds from cached hostfile
00:01:45.552  Getting requirements for /tmp/workspace/GitHub-custom-ci-builds/centos-7.8/s3-custom-build/rpms/s3/s3rpm.spec
00:01:45.553   --> Already installed : automake-1.13.4-3.el7.noarch
00:01:45.553   --> bazel-4.1.0-1.el7.x86_64
00:01:46.487   --> Already installed : …
```
=> [EOS-18251] Use Bazel 4.1.0 explicitly. 

server/s3_motr_writer.cc
1. S3_MOTR_MAX_UNITS_PER_REQUEST issue.
=> [EOS-21927] Motr Integration Issues

mempool/s3_memory_pool.c
Update s3_memory_pool.c. Avoid the unreleased lock pool->lock after the method returns. This patch for issue#1037.
=> avoid the unrelesed lock after the method returns for issue#1037

server/s3_put_object_action.cc
- Set pv_id into new object md (in-memory representation) as soon as it is created.
=> EOS-22262: PVID is null when object upload fails

server/s3_md5_hash.cc, server/s3_motr_context.cc, server/s3_motr_writer.cc, server/s3_motr_writer.h
<details>
<summary>Testing Done</summary>
> [root@ssc-vm-1453 testfiles]# s3cmd mb s3://seagatebucket
> motr[10641]:  a9f0  ERROR  [cas/service.c:1262:cas_fom_tick]  <! rc=-2
> motr[13646]:  9180  ERROR  [cas/client.c:1172:cas_req_replied_ast]  <! rc=-2
> Bucket 's3://seagatebucket/' created
> [root@ssc-vm-1453 testfiles]# ls
> total 223M
> -rw-r--r-- 1 root root 1.0K Jul 26 03:51 1kfile
> -rw-r--r-- 1 root root 2.0K Jul 26 03:51 2kfile
> -rw-r--r-- 1 root root 4.9K Jul 26 03:52 4kfile_unaligned
> -rw-r--r-- 1 root root 8.0K Jul 26 03:52 8kfile
> -rw-r--r-- 1 root root  16K Jul 26 03:52 16kfile
> -rw-r--r-- 1 root root  18K Jul 26 03:54 16kfile_unaligned
> -rw-r--r-- 1 root root  32K Jul 26 03:55 32kfile
> -rw-r--r-- 1 root root  33K Jul 26 03:55 32kfile_unaligned
> -rw-r--r-- 1 root root …
=> [EOS-23091] PUT Refactoring changes.

docs/CORTX-S3 Server Quick Start Guide.md
1. githubrelease is installed in /usr/local/bin. Need to add this to PATH to avoid error when run `./init.sh -a`.
2. Change git clone to use the HTTPS web URL. The benefit is that no need to generate SSH public key.
3. Add note to avoid Motr dependency conflict. For example, python may install a newer gcc version and conflict with Motr requirement, and cause './init.sh -a' failure.
-----
[View rendered docs/CORTX-S3 Server Quick Start Guide.md](https://github.com/wb-droid/cortx-s3server/blob/main/docs/CORTX-S3 Server Quick Start Guide.md)
=> update s3server guide with corrections

server/s3_motr_kvs_writer.cc, server/s3_motr_writer.cc, server/s3_motr_writer.h, server/s3_object_metadata.h, server/s3_post_complete_action.cc, server/s3_post_complete_action.h, server/s3_post_multipartobject_action.cc, server/s3_put_chunk_upload_object_action.cc, server/s3_put_object_action.cc, server/s3_put_object_action_base.cc, server/s3server.cc, third_party/build_motr.sh, ut/mock_s3_object_metadata.h, ut/mock_s3_object_multipart_metadata.h, ut/s3_motr_writer_test.cc, ut/s3_post_complete_action_test.cc, ut/s3_post_multipartobject_action_test.cc, ut/s3_put_chunk_upload_object_action_test.cc, ut/s3_put_object_action_test.cc
- S3server changes
- S3ut changes
- M0_ENF_META
- Motr version raised to 2ca587c61fdbd2b2b71c79ab0ebd8761e496f3ab
=> EOS-21164: All Motr object operations must supply PVID & LID

scripts/provisioning/cleanupcmd.py, scripts/provisioning/resetcmd.py, scripts/provisioning/setupcmd.py
- Cluster is not starting after reset phase
- removed the slapd shutdown from the reset phase
- truncate slapd log file instead of removing from reset and cleanup phase 
- added validation in start and stop services
=> EOS-23335: Truncate slapd log file instead of removing it

server/s3_object_metadata.cc
- object upload has "size" and its value as 0, it needs to be set to the content length, in case of fragmentation it will be different
-  Changed primary_obj_size from 0 to content_length.
=> [EOS-23164] : [Multipart Restructure] S3 multipart upload (Redesign) results in metadata "size" with value 0

server/s3_evbuffer_wrapper.cc, server/s3_motr_reader.cc
Add mempool logging in case of libevent call failure
due to memory crunch
=> Minor logging changes in case of memory crunch

server/s3_addb_map_auto.c, server/s3_post_complete_action.cc, server/s3_put_multiobject_action.cc, st/clitests/negative_spec.py, ut/s3_post_complete_action_test.cc
_[EOS-16893](https://jts.seagate.com/browse/EOS-23428):_
_Multipart Operations (GET, PUT) not working after rebase on MultipartRedesign branch_
- New object for extended metadata was being allocated. Removed that piece of code.
- State completed is never reached so used metadatasaved state in some cleanup tasks.
- Additional bugs that were uncovered related to old_oid were fixed.
=> [EOS-23428] Multipart Operations not working after rebase on MultipartRedesign branch.

scripts/kafka/message_bus.conf, server/s3_action_base.cc
- When we send copy-object request without authorization header, Error message was not in sync with aws s3.
- Aws error message : "Anonymous users cannot copy objects. Please authenticate"
- Cortx s3 error message : "Access Denied"
-  fixed s3server code and added error message
#**Testing output**:
=> EOS-21402:S3:Send complete error msg to client

server/s3server.cc
- Pass M0_ENF_META to S3 global indices
Also, store pv_id and layout_type values returned by Motr, w/out any condition check of whether ENF flag was set are not before invoking m0_entity_create.
Note: During dev testing, it was found that after setting M0_ENF_META in <idx.in_entity.en_flags, just before invoking m0_entity_create(), the flag is found to be getting reset to 0 after index create operation. So, removed condition check in code.
=> EOS-22190: Avoid lookup in Motr for S3 global indices

s3cortxutils/s3confstore/s3confstore/cortx_s3_confstore.py, scripts/provisioning/configcmd.py, scripts/provisioning/initcmd.py, scripts/provisioning/s3_haproxy_config.py, scripts/provisioning/s3setup_prereqs.json, scripts/provisioning/setupcmd.py
- Machine id should be get from the confstore instead of /etc/machine-id
- Create BG delete account should be moved to config phase.
- Machine id get from the confstore instead of /etc/machine-id
- Create BG delete account moved to config phase.
- 
=> EOS-23396: Machine ID and BGDelete account changes

installhelper.sh, rpms/s3/s3rpm.spec, scripts/provisioning/s3_start
- Create a single entry script s3_start to support argument: --service [ s3server | s3authserver | s3bgproducer | s3bgconsumer ]
-  Create basic structure for allowing all service provisioning separately.
=> EOS-23614 : Code changes for s3 single entry script with call to s3authserver script

scripts/provisioning/s3_start
Adding haproxy service handler and command to start haproxy inside container.
- Add haproxy to single entry-point script
-  Documented design changes [here](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/639434861/K8+single+node+deployment+without+systemd+on+VM+Only+for+S3+Internal+Purpose#1.-Configuration-changes-in-containers.)
=> EOS-22342 : Adding haproxy service handler

scripts/provisioning/s3_start
- Linux stream redirection was put in incorrect order, and so STDERR was actually being printed out to console for haproxy entry point script.
- Fix the order.
=> EOS-22342: Fix redirection in haproxy entry point script

scripts/provisioning/s3_start
- Auth server was not starting.
- Root cause -- now startauth.sh needs 1st arg = base path of config folder.
-  Modified s3_start to supply base config path to auth.
=> Auth server startup now takes config base path as 1st arg

scripts/provisioning/s3_start
=> [EOS-24264]: Config path changed to /etc/cortx for auth and s3 in startup script (PVC support)

auth/server/s3authserver.service, scripts/provisioning/s3_start
- s3_start script is not able to start auth server
- reason: wrong config base path: /etc/cortx, but expected is /etc/cortx/s3
=> EOS-24974: Fix auth base config path in startauth.sh argument

server/s3server.cc
=> EOS-24939: Terminate S3 server if motr_init got hung

scripts/provisioning/s3_haproxy_config.py, scripts/provisioning/s3_prov_config.yaml, scripts/provisioning/setupcmd.py
- HAproxy should read config path from confstore, remove hard-coding.
-  HAproxy should read config path from confstore, remove hard-coding.
=> HAproxy should read config path from confstore.

scripts/provisioning/configcmd.py
- Storage set count is removed from the confstore. 
- Openldap is still using storage set count
Fixed the opeldap schema as per new constore changes
=> EOS-24396: Fixed the opeldap schema as per new constore changes

server/s3server.cc
=> [K8 Bug] EOS-25051:S3: Increase motr init time from 15s -> 60s

scripts/provisioning/configcmd.py, scripts/provisioning/s3_prov_config.yaml
-----
[View rendered docs/notes.md](https://github.com/Seagate/cortx-s3server/blob/br/vr/motr_retry_interval/docs/notes.md)
[View rendered s3backgrounddelete/readme.md](https://github.com/Seagate/cortx-s3server/blob/br/vr/motr_retry_interval/s3backgrounddelete/readme.md)
=> EOS-25740: Motr retry timout should be read from constore and set in to config file

server/s3_bucket_metadata.cc, server/s3_motr_kvs_reader.cc, server/s3server.cc
* Clear bucket metadata object before reloading from Motr.
* Fix misprints in log messages.
* Add extra logging for get_keyval.
- s3 would sometimes return stale bucket tags, even after bucket MD cache timeout passes.
- For Bug, Describe the fix here.
- Properly clear cache entry before loading from Motr.
=> EOS-25359: Clear bucket metadata object before reloading from Motr.

jenkins-build.sh, rebuildall.sh
With this change, it is now possible to quicker test s3server changes, by running this below command:
```
./jenkins-build.sh --no_clean_build --build_only_s3server --skip_tests
```
This will only build/rebuild s3server, and leave other targets as is.
- Even a single file change in s3server would cause rebuild of all other tools as well (Java, kvscli, etc).
-  Add CLI option to bypass everything but s3server.
=> EOS-25783: Add options to jenkins-build.sh to speed up s3server rebuild.

server/s3_object_metadata.cc
=> EOS-19900 [s3faulttolerance bug] :  Parsing of extended metadata key, since object name can contain delimiter |

scripts/ldap/s3_setup_ldap.sh, scripts/provisioning/configcmd.py, scripts/provisioning/setupcmd.py, scripts/provisioning/templates/s3.config.tmpl.1-node, scripts/provisioning/templates/s3.config.tmpl.1-node.sample, scripts/provisioning/templates/s3.config.tmpl.3-node, scripts/provisioning/templates/s3.config.tmpl.3-node.sample
- Remove hardcoding username (sgiamadmin) and password in symas openldap image and config phase
=> [EOS-26114]: Remove hardcoding username (sgiamadmin) and password in symas openldap image and config phase

s3backgrounddelete/s3backgrounddelete/object_recovery_validator.py, server/s3_addb_map_auto.c, server/s3_post_complete_action.cc, server/s3_post_complete_action.h, server/s3_put_chunk_upload_object_action.cc, server/s3_put_chunk_upload_object_action.h, server/s3_put_multiobject_action.cc, server/s3_put_multiobject_action.h, server/s3_put_object_action.cc, server/s3_put_object_action.h, st/clitests/negative_spec.py, ut/s3_post_complete_action_test.cc, ut/s3_put_chunk_upload_object_action_test.cc, ut/s3_put_object_action_test.cc
Signed-off-by: Dattaprasad Govekar <dattaprasad.govekar@seagate.com>
-  Parallel operations lead to object leak
-  Handling object leak due to parallel S3 operations (POST complete, multipart PUT, simple PUT)
=> EOS-25627: Handle parallel multipart POST complete and Put part operations

server/s3_delete_multiple_objects_action.cc, server/s3_delete_multiple_objects_action.h
- S3server crashes when doing batch-delete of several multipart-uploaded objects.
-  Root cause -- array index was not reset to 0 after completing delete of first object.  So on second object it was going out of range.
=> EOS-26807: Bugfix: Reset array index on a next iteration.

scripts/provisioning/configcmd.py, scripts/provisioning/initcmd.py, scripts/provisioning/s3_start, scripts/provisioning/setupcmd.py, scripts/provisioning/upgradecmd.py
Services separation in s3_start 
Services separation in s3_start 
-----
[View rendered docs/notes.md](https://github.com/Seagate/cortx-s3server/blob/br/vr/EOS-26572-III/docs/notes.md)
[View rendered s3backgrounddelete/readme.md](https://github.com/Seagate/cortx-s3server/blob/br/vr/EOS-26572-III/s3backgrounddelete/readme.md)
=> EOS-26572: Services separation in s3_start, rename of BG services 

server/s3_addb_map_auto.c, server/s3_put_bucket_versioning_action.cc, server/s3_put_bucket_versioning_action.h, st/clitests/awss3api_spec.py, ut/s3_put_bucket_versioning_action_test.cc
- For PI-5 we should not allow users to suspend versioning.
- Putbucketversioning with suspended versioning should return an error.
- Versioning should be enabled and disabling should return a message - call not supported.
- If a bucket already has objects, versioning cannot be enabled on it.  
- Disable the UT/ST for the suspended test.
Design docs not prepared as this is a temporary change.
=> [versioning] [EOS-26658] Preventing bucket to go in suspended state [temporary]

auth/server/src/test/java/com/seagates3/dao/ldap/UserPolicyLdapStoreTest.java
- Unit tests for attach and detach IAM policy.
-  NA
- http://eos-jenkins.colo.seagate.com/job/S3server/job/S3Server-PreMerge-Test/784/
Signed-off-by: Shri Metta <shri.metta@seagate.com>
=> [iam policy] EOS-25967: Unit tests for IAM Policy attach and detach

auth-utils/jclient/pom.xml, auth/encryptcli/pom.xml, auth/encryptutil/pom.xml, auth/server/pom.xml
- Updating log4j package version to 2.15.0
- Most recent version of log4j is 2.15.0
- Earlier versions of log4j are vulnerable to CVE-2021-44228
Corresponding story is raised here -> https://jts.seagate.com/browse/EOS-26894
Earlier versions of log4j are vulnerable to CVE-2021-44228
Fix ix to upgrade log4j version to the latest version
-  [X] Coding conventions are followed and code is consistent
its  3rd party library upgrade
NA
=> Update log4j package version

auth-utils/jclient/pom.xml, auth/encryptcli/pom.xml, auth/encryptutil/pom.xml, auth/server/pom.xml
Another vulnerability is reported on log4j library CVE-2021-45046 with Low CVSS score of 3.7
Which means, the severity is LOW
However since a newer version of log4j (v 2.16.0 ) is available, it will be upgraded
So reopening this issue to upgrade log4j library to v 2.16.0
Another vulnerability is reported on log4j library CVE-2021-45046 with Low CVSS score of 3.7
Link to Story -> https://jts.seagate.com/browse/EOS-26894
References to org.apache.logging.log4j version changed to 2.16.0
Not applicable
Not applicable
Checklist for …
=> Upgrade log4j to 2.16.0

server/s3_put_multiobject_copy_action.cc, server/s3_put_multiobject_copy_action.h
Signed-off-by: Sumedh A. Kulkarni <sumedh.a.kulkarni@seagate.com>
The newly added {{s3_put_multiobject_copy_action.h/cc}} classes does not follow the syntax as per clang standard, which results in the error while running {{jenkins-build.sh.}}
Error:
```
One or more modified files do not comply with clang-format.
Running below command to see required changes:
'git clang-format --style=Google --extensions=c,cc,h,java --diff --commit HEAD~1'
====================================================================
diff --git a/server/s3_put_multiobject_copy_action.cc b/server/s3_put_multiobject_copy_action.cc
index 66de8503..f8adfeaa 100644
--- a/server/s3_put_multiobject_copy_action.cc
+++ b/server/s3_put_multiobject_copy_action.cc
@@ -51,15 +51,16 @@ …
```
=> EOS-27020 [Fix] Clang Error in jenkins-build.sh 

server/s3_data_usage.cc
- Server ID is hard-coded to "1" now; need to use real server ID.
-  Using server motr EP address as server ID.
=> EOS-27000: Use Motr EP address as unique server ID for DataUsage

server/s3_data_usage.cc
- Negative counter values were saved as huge positive integers.
-  Use Int64 instead of UInt64.
-----
[View rendered docs/notes.md](https://github.com/Seagate/cortx-s3server/blob/br/it/EOS-27000-bugfix-negative-counters/docs/notes.md)
[View rendered s3backgrounddelete/readme.md](https://github.com/Seagate/cortx-s3server/blob/br/it/EOS-27000-bugfix-negative-counters/s3backgrounddelete/readme.md)
=> EOS-27000: bugfix for negative counters

server/s3_addb_plugin_auto.cc, server/s3_addb_plugin_auto.h, server/s3_data_usage_action.cc, server/s3_data_usage_action.h, server/s3_management_api_handler.cc
- [EOS-26536](https://jts.seagate.com/browse/EOS-26536): stub out the data usage API for CSM (/s3/data_usage).
-  The stub returns `[ "12345": { "bytes_count": 123456789 }, "54321": { "bytes_count": 987654321 } ]`
=> [F-71A] [data-usage] EOS-26536: Enabler - stub out API for CSM

server/s3_get_object_action.cc, server/s3_get_object_action.h, server/s3_object_metadata.h, ut/mock_s3_object_metadata.h, ut/s3_get_object_action_test.cc
For GetObject API, handle the case when requested object is a delete marker -  
- If the latest object is a delete marker , return error - NoSuchKey.
- If specified versionId belongs to a delete marker, return error - MethodNotAllowed.
Jira - https://jts.seagate.com/browse/EOS-25996
- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/766902714/GetObject+LLD
=> [versioning] EOS-25996: GetObject - deleteMarker

server/s3_get_object_action.cc, server/s3_object_metadata.h, ut/s3_get_object_action_test.cc
Signed-off-by: Dattaprasad Govekar <dattaprasad.govekar@seagate.com>
- Range based Get object on multipart uploaded object fails when first byte offset of range does
not coincide with the start of the data block unit. The issue is seen only when max units read/write per request is more than one (say, 8 or 32)
-  Handled situation when the first byte range is not aligned to start of data block
=> EOS-26811: Get object with range read is not working on multipart-uploaded object

server/request_object.cc, server/request_object.h, server/s3_addb.h, server/s3_motr_kvs_writer.cc
EOS-24139: Use addb ID generation API from motr, instead of incremental counter
- Current code to generate ADDB uses incremental counter -- this is recently creating problems for PerfLine team, they asked to use API generator API from Motr.
=> EOS-24139: Use addb ID generation API from motr

server/s3_object_data_copier.cc, server/s3_object_data_copier.h, server/s3_put_multiobject_copy_action.cc, server/s3_put_multiobject_copy_action.h
- Multipart upload part copy based on range specified in `x-amz-copy-source-range`
-  Modified `s3_object_data_copier.cc` to support range based copy.
-  Added extra validations for range based copy.
> Unit tests will be updated with [#1725](https://github.com/Seagate/cortx-s3server/pull/1725)
=> [multipart-partcopy] EOS-24345: Part Copy Based on Specified Range for Simple Objects

server/s3_bucket_metadata.h, server/s3_data_usage.cc, server/s3_data_usage.h, ut/mock_s3_bucket_metadata.h, ut/s3_data_usage_cache_test.cc
- Add UTs for data usage cache, implemented in EOS-26532.
- Add unit tests for DataUsageItem with mocked KVS reader/writer
- Add mock class for DataUsageItem
- Add unit tests for DataUsageCache with mocked DataUsageItem
=> [data-usage] EOS-26924: UT for data usage cache

server/s3_addb_map_auto.c, server/s3_data_usage.cc, server/s3_data_usage.h, server/s3_data_usage_action.cc, server/s3_data_usage_action.h, ut/s3_data_usage_action_test.cc
- [EOS-26626](https://jts.seagate.com/EOS-26626): API for CSM
- Full implementation of Accounts Data Usage API from S3 to CSM
- [Design page in Confluence](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/782663777/Option+3+store+counters+in+dedicated+index+in+Motr+per+instance+per+account)
=> [data-usage] EOS-26626: API for CSM

server/s3_list_object_versions_action.cc, server/s3_list_object_versions_action.h, st/clitests/awss3api_spec.py, ut/s3_list_object_versions_action_test.cc
Implement additional UT and ST for List Object Versions API
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/766050414/ListObjectVersions+LLD
=> [versioning] EOS-26911: Implemented additional UT and ST for List Object Versions API

s3backgrounddelete/s3backgrounddelete/object_recovery_msgbus.py, s3backgrounddelete/s3backgrounddelete/object_recovery_scheduler.py, s3cortxutils/s3msgbus/s3msgbus/cortx_s3_msgbus.py
MessageBus library is removing API get_unread_count. Remove all references to this API from S3 code
Update S3 background delete code, so that it do not make use of get_unread_count method provided by MessageBus Library.
=> [EOS-26912] Remove refs to get_unread_count

server/s3_object_metadata.cc, server/s3_object_metadata.h, server/s3_put_object_action.cc, server/s3_put_object_action.h, ut/mock_s3_factory.h, ut/mock_s3_object_metadata.h, ut/s3_put_object_action_test.cc
PutObject when bucket versioning is suspended.
Jira: https://jts.seagate.com/browse/EOS-25874
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/768639283/PutObject+LLD
=> [versioning] [EOS-25874] - PutObject with null version

format-code.sh, runut.sh, s3build.sh, s3log.sh, st/clitests/awss3api_spec_short.py, utbuild.sh
I have created few scripts to make it easy for developer to access different logs, do incremental builds, run UTs with specific filters and develop & test STs. Basically reducing some manual steps.
**s3log.sh** - To access different logs for services like s3server, auth-server, background delete.
```
Usage:
-i : For info logs.
-d : For debug logs.
-w : For warning logs.
-e : For error logs.
-a : To see auth server logs. Can not be used along with -b.
-b : To see background processor logs. Can not be used along with -a.
-s : To see background schedular logs. To be used along with -b.
-t : To tail log file. Can not be used with -v option.
-v : To open log in vim editor. Can not be used with -t option.
-h : For usage.
```
**s3build.sh** - To build s3server code and install s3server binary. …
=> [EOS-26854] Adding dev scripts.

scripts/provisioning/s3_start
Signed-off-by: Swapnil Chaudhary <swapnil.chaudhary@seagate.com>
- We have increased the timeout for start up script, hence there was no need of the retry mechanism. 
-  Remove the retry mechanism for s3_start script, before starting the service.
-  [ Y] Coding conventions are followed and code is consistent
Performed Test on 3N and 15N set-up. The results are uploaded on JIRA ticket.
- [Y ] JIRA number/GitHub Issue added to PR
- [ Y] PR is self reviewed
- [ Y] Jira and state/status is updated and JIRA is updated with PR link
- [ Y] Check if the description is clear and explained
=> EOS-25051: Removed the retry loop from s3_start init script.

auth/server/src/main/java/com/seagates3/controller/AccountController.java, auth/server/src/main/java/com/seagates3/dao/ldap/AccountImpl.java
- CSM REST: Create S3 account failed with 500 ('InternalFailure' is not a valid IamErrors)
-  This error is occurring due to data inconsistency between the nodes as replication operation is not happening properly. Hence added delays in between ldap operations to give time to OpenLDAP to replicate the data in other nodes.
=> EOS-26124: Added delays in between ldap operations while create and delete S3 accounts

server/s3_copy_object_action.cc
Quick update to add replication support to CopyObject. This follows essentially the same steps as the other put-related API changes, with minor adjustments for source/destination buckets in this operation. I tested in a VM, seems to work as expected.
@shraddhaghatol @mbcortx Could you review?
For EOS-26850
Signed-off-by: Tim Shaffer <tim.shaffer@seagate.com>
=> [replication] Update CopyObject to apply destination bucket replication policy

server/s3_get_object_action.cc
The issue is previous code changes for multipart object were executed
for simple object. Fixed this by making code changes exclusively for multipart object.
Signed-off-by: Dattaprasad Govekar <dattaprasad.govekar@seagate.com>
=> EOS-27323: Fix for range read of object.
