- server/request_object.cc
- server/request_object.h
- server/s3_bucket_action_base.cc
- server/s3_get_multipart_part_action.cc
- server/s3_object_action_base.cc
- server/s3_put_object_action.cc
- server/s3_request_object.cc
- server/s3_router.cc
- server/s3_service_api_handler.cc
- server/s3server.cc
Health check (HEAD request) comes frequently, optimized
logging to take less log space. Did few other changes also
relating to logging
> EOS-13578: S3 log changes, so as to use less space

- CONTRIBUTING.md
- README.md
- SECURITY.md
- SUPPORT.md
- docs/CORTX-S3 Server Quick Start Guide.md
> Updated Contribution guide

- scripts/provisioning/setup.yaml
> [LDR R2] Move log rotate config from post_install action to config

- scripts/provisioning/setup.yaml
> [LDR R1] EOS-13852 : changes for M5

- s3recovery/s3recovery/s3recoverybase.py
> [LDR-R1] EOS-13832 : Handle Json parsing TypeError

- ut/s3_common_utilities_test.cc
> EOS-13860: Fix issue in UT

- auth/resources/authserver.properties
- auth/resources/keystore.properties
13987 fix rollback because of build failure
> EOS-13987 revert build failure

- s3mempoolmgrut/s3_mem_pool_mgr_test.cc
- server/motr_common.cc
- server/s3server.cc
- ut/s3_server_tests.cc
- ut_death_tests/s3_server_tests.cc
> [LDR-R1]EOS-14041: Do some parallel execution to reduce shutdown time

- server/s3_head_object_action.cc
> [LDR-R1]EOS-14077: Fix for content-type in Head object API

- s3config-test.yaml
- s3config.release.yaml
- s3config.yaml
- server/s3_asyncop_context_base.h
- server/s3_common_utilities.cc
- server/s3_common_utilities.h
- server/s3_motr_rw_common.cc
- server/s3_option.cc
- server/s3_option.h
- server/s3server.cc
- ut/mock_s3_asyncop_context_base.h
- ut/mock_s3_request_object.h
- ut/s3_motr_rw_common_test.cc
> [LDR-R1] EOS-14001: Handle motr timeout error by restart in case of high error rate

- server/s3server.cc
> EOS-14137: Removed fatal signal handler registration.

- auth/encryptcli/pom.xml
- auth/encryptutil/pom.xml
- auth/server/pom.xml
Fixing log4j warnings flagged by depandabot about log4j version
We will handle netty warning seperatly since it required more work for UT failures
> [INP] EOS-13682:S3: bump version of log4j 

- ansible/files/yum.repos.d/centos7.7.1908/cortx.repo
- ansible/files/yum.repos.d/centos7.8.2003/cortx.repo
- ansible/files/yum.repos.d/centos7.8.2003/cortx_s3_deps.repo
- scripts/env/common/setup-yum-repos.sh
- scripts/env/dev/init.sh
Added new repo files for centos-7.8.2003 and updated checks for Platofrms and kernel version.
> EOS-14100: [LDR R1] Add support for CentOS-7.8.2003 for S3 dev Environment

- auth/encryptcli/pom.xml
- auth/encryptutil/pom.xml
- auth/server/pom.xml
- s3web/README.rdoc
Bump up Junit version,
Old value  : 4.12
New value : 4.13.1
> EOS-14296:Auth:bump up junit version 4.12 -> 4.13.1

- scripts/s3-support-bundles/s3_bundle_generate.sh
Collect rotated logs of haproxy and slapd if available
> [LDR-R1] EOS-14343:s3: collect rotated logs of haproxy and ldap

- server/motr_common.cc
- server/motr_helpers.h
- server/s3server.cc
> EOS-14252: [INP] Retry for global index creation failure

- ansible/common_runtime.yml
- installhelper.sh
- rpms/s3/s3rpm.spec
- scripts/s3-logrotate/s3addblogfilerollover.sh
> EOS-14599:Addb rotation changes

- docs/CORTX-S3 Server Quick Start Guide.md
Refer to [issue 334](https://github.com/Seagate/cortx-s3server/issues/334).
> Fix disable selinux command

- docs/CORTX-S3 Server Quick Start Guide.md
Updated Quickstart Guide with Pip install
> Updated Quickstart Guide with Pip install

- docs/authserver_notes.rst
Moved authserver_notes.rst from CORTX parent to S3
> Moved authserver_notes.rst from CORTX parent to S3

- docs/CORTX-S3 Server Quick Start Guide.md
Updated CORTX-S3 Server Quick Start Guide.md
> Updated CORTX-S3 Server Quick Start Guide.md

- addb/readme
- jenkins-build.sh
- rpm-deploy.sh
- s3config.release.yaml.sample
- s3config.yaml.sample
- scripts/fio/runall.sh
- scripts/s3-logrotate/s3addblogfilerollover.sh
- scripts/s3-logrotate/s3m0tracelogfilerollover.sh
- scripts/s3-support-bundles/s3_bundle_generate.sh
> EOS-14911 [LDR-R1] changes for log directory move to  /var/log/seagate/motr

- server/request_object.cc
- st/clitests/s3kvs.py
Splunk test failure fix
AWS/Splunk Expected      : x-amz-request-id
S3 response                     : x-amzn-RequestId 
Hence replacing request code as per aws
> EOS-14824: [Splunk] S3:update x-amzn-RequestId with x-amz-request-id

- server/s3_get_bucket_action.cc
- server/s3_head_bucket_action.cc
- server/s3_service_list_response.cc
Added connection close header to HEAD bucket response when the request fails. This is in compliance with AWS behavior.
> EOS-14979 splunk no such bucket issue

- m0kv_metadata_parsing_tool/README.md
- m0kv_metadata_parsing_tool/m0kv_metadata_parsing_tool.sh
> EOS 14891 : Removed aws dependency for m0kv_metadata_parsing_tool.

- server/base64.cc
- ut/base64_test.cc
> EOS-14459: base64 refactoring

- scripts/audit_log/audit_logs_proc.py
> Add script for audit logs parsing

- auth/resources/authserver.properties.sample
- auth/server/src/main/java/com/seagates3/authserver/AuthServerConfig.java
- auth/server/src/main/java/com/seagates3/dao/ldap/AccountImpl.java
- auth/server/src/main/java/com/seagates3/dao/ldap/LDAPUtils.java
- auth/server/src/main/java/com/seagates3/dao/ldap/UserImpl.java
- auth/server/src/test/java/com/seagates3/dao/ldap/AccountImplTest.java
- auth/server/src/test/java/com/seagates3/dao/ldap/LDAPUtilsTest.java
- auth/server/src/test/java/com/seagates3/dao/ldap/UserImplTest.java
- scripts/ldap/resultssizelimit.ldif
- scripts/ldap/setup_ldap.sh
Signed-off-by: Basavaraj Kirunge <basavaraj.kirunge@seagate.com>
> EOS-15111 increase ldapsearch result size limit

- server/s3_bucket_metadata_v1.cc
- server/s3_bucket_metadata_v1.h
- ut/s3_bucket_metadata_v1_test.cc
> EOS-8749: Revert global indexes on create bucket error

- server/s3_motr_rw_common.cc
> Print error code on stable with error log level

- docs/CORTX-S3 Server Quick Start Guide.md
> Updated last tested

- docs/CORTX-S3 Server Quick Start Guide.md
Updated Before you begin section as per review on issue https://github.com/Seagate/cortx-motr/issues/217
> Updated Before you begin section

- ansible/common_runtime.yml
- scripts/env/dev/init.sh
- scripts/env/release/init.sh
- scripts/haproxy/haproxy_osver7.cfg
- scripts/haproxy/haproxy_osver8.cfg
Upgrade haproxy version of dev environment,
Current version   : 1.5.18-9.el7
Upgrade version :  1.8.14-1.el7
Updated haproxy and dependency packages are available on our repo http://cortx-storage.colo.seagate.com/releases/cortx/uploads/centos/centos-7.8.2003/s3server_uploads/  as part of EOS-15252
> EOS-14843:S3: upgrade haproxy version to v1.8.14-1.el7

- st/clitests/awss3api_spec.py
> EOS:15091 - Added System Tests related to source metadata load and validation.

- server/s3_get_bucket_action.cc
Solution/Changes:
- After every key fetch set (idx fetch count=30), check if client read timeout
has occurred. If so, stop further object enumeration from Motr, and terminate the request processing.
- Fixed issue during dev testing.
> EOS-15038: Fix for Client read timeout due to object listing taking

- auth/server/src/main/java/com/seagates3/authentication/AWSV2Sign.java
- auth/server/src/main/java/com/seagates3/authentication/AWSV4Sign.java
- auth/server/src/main/java/com/seagates3/authentication/ClientRequestParser.java
- auth/server/src/main/java/com/seagates3/authentication/SignatureValidator.java
- auth/server/src/main/java/com/seagates3/authserver/AuthServerGetHandler.java
- auth/server/src/main/java/com/seagates3/controller/IAMController.java
- auth/server/src/main/java/com/seagates3/controller/SAMLWebSSOController.java
- auth/server/src/main/java/com/seagates3/dao/ldap/LDAPUtils.java
- auth/server/src/main/java/com/seagates3/dao/ldap/LdapConnectionManager.java
- auth/server/src/main/java/com/seagates3/util/ACLPermissionUtil.java
- auth/server/src/main/java/com/seagates3/util/AWSSignUtil.java
- auth/server/src/main/java/com/seagates3/util/BinaryUtil.java
- auth/server/src/main/java/com/seagates3/util/DateUtil.java
- auth/server/src/main/java/com/seagates3/util/XMLValidatorUtil.java
- s3backgrounddelete/s3backgrounddelete/IEMutil.py
- server/s3_iem.h
Signed-off-by: Pranav <pranav.pawar@seagate.com>
> EOS-15343 : S3 IEM Alerts correction/improvement

- docs/CORTX-S3 Server Quick Start Guide.md
Updated S3 Server prerequisites
> Updated S3 Server prerequisites

- docs/CORTX-S3 Server Quick Start Guide.md
added steps to start haproxy in section 1.4 step 4
> added steps to start haproxy in section 1.4 step 4

- server/s3_copy_object_action.cc
- server/s3_copy_object_action.h
- server/s3_motr_reader.cc
- server/s3_motr_reader.h
- ut/mock_s3_motr_reader.h
- ut/s3_copy_object_action_test.cc
> EOS-15555: copy object optimization

- rebuildall.sh
- s3backgrounddelete/s3backgrounddelete/config/s3_background_delete_config.yaml.sample
- s3backgrounddelete/s3backgrounddelete/cortx_s3_config.py
- s3backgrounddelete/s3backgrounddelete/cortx_s3_constants.py
- s3backgrounddelete/s3backgrounddelete/object_recovery_msgbus_consumer.py
- s3backgrounddelete/s3backgrounddelete/object_recovery_processor.py
- s3cortxutils/s3msgbus/s3msgbus/cortx_s3_msgbus.py
- s3cortxutils/s3msgbus/s3msgbus/s3_msgbus_example
- s3cortxutils/s3msgbus/setup.py
1. Added config option to use message bus in yaml.
2. Changes for loading the config option from yaml file.
3. Added msgbus_consumer class that will interact with messagebus.
4. Made changes to recovery processor to select rabbitmq or msgbus
based on config option.
> S3:EOS-15685: S3background delete Consumer porting to Message Bus

- third_party/build_motr.sh
> Support parallel Motr build when multiple processors/cores are available

- docs/sequencediagrams/delete-multiple-objects-activity.plantuml
> EOS-15186: Minor improvement to batch-delete diagram.

- rpms/s3/s3rpm.spec
> Do not build UTs and disable java tests during RPM build.

- s3cortxutils/s3confstore/s3confstore/cortx_s3_confstore.py
- scripts/ldap/replication/setupReplicationScript.sh
- scripts/provisioning/s3_setup
Also update setupReplicationScript.sh to read host names from a comm-separated string,
instead of a text file.
> EOS-16238: Update s3_setup script to read confstore config file URL as cmdline argument.

- s3backgrounddelete/s3backgrounddelete/cortx_s3_index_api.py
> S3:EOS-16428: Changed keys to max-keys.

- scripts/coverage/run_all_coverage.sh
Add codacy token as an argument to the coverage script.
> EOS-16099 : Add Codacy token as an argument to the script for code coverage

- s3backgrounddelete/s3backgrounddelete/config/s3_background_delete_config.yaml.sample
- st/clitests/backgrounddelete_spec.py
- st/clitests/s3_background_delete_config_test.yaml
Defaulting to rabbit_mq for now as kafka installation and topic creation and pyutils dependency issues not resolved currently in init script.
ST's may use rabbit_mq or message_bus depending on configuration value.
Jenkins Job : http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server-7.8.2003/403/console
> Changes required to make background ST's run.

- server/evhtp_wrapper.cc
- server/evhtp_wrapper.h
- server/request_object.cc
- server/request_object.h
- server/s3_copy_object_action.cc
- server/s3_copy_object_action.h
- server/s3_error_codes.cc
- server/s3_error_codes.h
- ut/mock_evhtp_wrapper.h
- ut/mock_motr_request_object.h
- ut/mock_s3_request_object.h
- ut/s3_copy_object_action_test.cc
> EOS-16472: copy large objects

- rpms/s3/s3rpm.spec
- rpms/s3iamcli/s3iamcli.spec
Update version values of s3server, s3iamcli rpms based on input parameter.
e.g.
cd /root/cortx-s3server
./rpms/s3/buildrpm.sh -S 1.0.2-P /root/cortx-s3server
> Update rpm version value as per input parameter

- server/evhtp_wrapper.cc
- server/s3_copy_object_action.cc
> EOS-16032: some enhancemant

- s3cortxutils/s3confstore/s3confstore/cortx_s3_confstore.py
- s3cortxutils/s3confstore/s3confstore/s3confstore
- s3cortxutils/s3confstore/ut/s3confstore_unit_tests.py
- scripts/env/dev/init.sh
- server/s3_copy_object_action.cc
Added new APIs for getting privateip, nodescount and hostnames.
Re-factored the s3confstore to be called efficiently from python code.
> EOS:16672 update s3confstore APIs

- scripts/kafka/install-kafka.sh
Changed source directory path in kafka script
> EOS-16218:S3: Changed source directory path in kafka script

- installhelper.sh
- rpms/s3/s3rpm.spec
- scripts/provisioning/s3_setup
- scripts/provisioning/s3setup/s3setup/cortx_s3_setup.py
- scripts/provisioning/s3setup_prereqs.json
- scripts/provisioning/setup.yaml
commit 99e3cf612061efb0db227faa44fa12ee05100c9b
Date:   Fri Jan 22 03:29:51 2021 -0700
EOS-16423: S3 Mini-provisioner: Validations in post_install
Address Amit and Ajinkya's review commentsi to adhere the new format of command args for s3setup
Files edited/added:
modified:   scripts/provisioning/s3_setup
modified:   scripts/provisioning/s3setup/s3setup/cortx_s3_setup.py
modified:   scripts/provisioning/setup.yaml
Testing done:
Unit tested s3setup changes on VM
Signed-off-by: pratyush-seagate <pratyush.k.khan@seagate.com>
commit 5381df60b08a1e1a3f8d2049f11f7681a8f94a8a
Date:   Thu Jan 21 11:42:50 2021 -0700
EOS-16423: S3 Mini-provisioner: Validations in …
> EOS-16423: S3 Mini-provisioner: Validations in post_install [PR#639 continuation with main]

- scripts/ldap/replication/setupReplicationScript.sh
- scripts/provisioning/s3_setup
> EOS:16996 - Add post_install validation in 's3_setup post_install' 

- rpms/s3/s3rpm.spec
Reverts Seagate/cortx-s3server#655
> Revert "Add soft link to s3_setup script in /usr/local/bin"

- scripts/provisioning/setup.yaml
> EOS:17185 - Give absolute path of s3_setup script in setup.yaml

- s3cortxutils/s3cipher/s3cipher/cortx_s3_cipher.py
Signed-off-by: vimalraghwani20 <vimal.raghwani@seagate.com>
> EOS-16666:S3: Fix the cipher changes for mini-provision

- server/s3_get_bucket_action.cc
- server/s3_object_metadata.h
- Changes to skip listing of extended entries from object list index.
(cherry picked from commit ec346995039cb92fbdecc8636b3523c0e8df727d)
> EOS-16889: s3faulttolerence - Changes in Object listing

- s3cortxutils/s3confstore/s3confstore/cortx_s3_confstore.py
- s3cortxutils/s3confstore/ut/s3confstore_unit_tests.py
- scripts/haproxy/s3haproxyconfig/s3haproxyconfig/s3_haproxy_config.py
EOS-16872 : LDRr2: Configure HAProxy as a part of S3 setup 3 Node VM component provisioning
Made fixes to add "s3 server port" and get public_ip from s3confstore.
Files modified :
s3cortxutils/s3confstore/s3confstore/cortx_s3_confstore.py
scripts/haproxy/s3haproxyconfig/s3haproxyconfig/s3_haproxy_config.py
> EOS-16872 : LDRr2: Configure HAProxy as a part of S3 setup 3 Node VM component provisioning

- server/s3_object_metadata.h
> Code formatting issue due to the fix in EOS-17129 is fixed.

- scripts/provisioning/s3_setup
- scripts/provisioning/s3setup/s3setup/cortx_s3_setup.py
- scripts/provisioning/s3setup_prereqs.json
commit a6c23ac6e98f4b45afec23661db22410637a36e5
Date:   Thu Jan 28 02:02:12 2021 -0700
EOS-17069: Add new file validator and add additional validations in post_install prerequisites
Integrate new validator API for checking files with s3setup's post_install prerequisites validator
Update the installed prerequisites json file with additional details as provided
Added/modified/deleted files:
modified:   s3setup/cortx_s3_setup.py
modified:   ../s3setup_prereqs.json
Unit test:
Run "s3setup post_install" with updated s3setup_prereqs.json and verified changes are working as expected.
Signed-off-by: pratyush-seagate <pratyush.k.khan@seagate.com>
> EOS-17069: Add new file validator and add additional validations in post_install prerequisites

- kv-schema/schema_v1.0.yaml
> EOS-16693: schema definition file

- scripts/create_auth_jks_password.sh
- scripts/ldap/setup_ldap.sh
- scripts/provisioning/s3_setup
> EOS:16994 - Add error handling in s3_setup script

- README.md
Added the YouTube, and Slack badges. Also, correct the Codacy badge.
Signed-off-by: Mayur Gupta `mayur.gupta@seagate.com`
-----
[View rendered README.md](https://github.com/TechWriter-Mayur/cortx-s3server/blob/main/README.md)
> Added the badges

- server/s3_addb_map_auto.c
- server/s3_object_metadata.cc
- server/s3_object_metadata.h
- server/s3_post_multipartobject_action.cc
- server/s3_post_multipartobject_action.h
- ut/s3_post_multipartobject_action_test.cc
1) Removal of motr oid creation
2) Appending upload id to object name and some other changes
> EOS-17265: Initiate multipart upload as per new design

- auth/server/src/main/java/com/seagates3/dao/ldap/LdapConnectionManager.java
- auth/server/src/main/java/com/seagates3/util/ACLPermissionUtil.java
- auth/server/src/main/java/com/seagates3/util/DateUtil.java
- auth/server/src/main/java/com/seagates3/util/XMLValidatorUtil.java
- s3backgrounddelete/s3backgrounddelete/cortx_s3_index_api.py
- s3backgrounddelete/s3backgrounddelete/cortx_s3_kv_api.py
- s3backgrounddelete/s3backgrounddelete/cortx_s3_object_api.py
- s3backgrounddelete/s3backgrounddelete/object_recovery_queue.py
- s3backgrounddelete/s3backgrounddelete/object_recovery_scheduler.py
- server/motr_common.cc
- server/s3_abort_multipart_action.cc
- server/s3_auth_client.cc
- server/s3_bucket_metadata.cc
- server/s3_chunk_payload_parser.cc
- server/s3_delete_bucket_action.cc
- server/s3_delete_multiple_objects_action.cc
- server/s3_iem.h
- server/s3_motr_rw_common.cc
- server/s3_part_metadata.cc
- server/s3_post_multipartobject_action.cc
- server/s3_put_chunk_upload_object_action.cc
- server/s3_put_object_action.cc
- server/s3_uri_to_motr_oid.cc
- server/s3server.cc
Signed-off-by: abhilekh <abhilekh.mustapure@seagate.com>
> [EOS-17428] IEM/Fault observed "failed to connect to RabbitMq"

- requirements.txt
- scripts/ldap/create_account_using_cipher.py
- scripts/ldap/ldapaccountaction.py
- scripts/provisioning/cleanupcmd.py
- scripts/provisioning/initcmd.py
- scripts/provisioning/s3_setup
- scripts/provisioning/s3setup_prereqs.json
> EOS:16997 - Refactor cleanupcmd python file: Move delete ldap account code to ldapaccountaction file.

- server/s3_get_bucket_action.cc
- server/s3_get_bucket_action.h
- server/s3_object_list_response.cc
- server/s3_object_list_response.h
- ut/s3_get_bucket_action_test.cc
The fix is basically cherry-picked from 'main' branch @ commit id 2789e03b73095b37b348f48d02d0d18d7a692b99
> [Merge_into_R1] Fix for EOS-18435 - object listing timeout issue

- docs/sequencediagrams/auth-combined-call.plantuml
Simply removing the comment -- diagram itself does not change.
> Fix the diagram (remove wrong comment, it was breaking the rendering).

- s3backgrounddelete/s3backgrounddelete/object_recovery_msgbus.py
- s3cortxutils/s3msgbus/s3msgbus/cortx_s3_msgbus.py
> EOS-12724:[MsgBus] Convert s3background delete consumer msgbus calls from non-blocking to blocking.

- docs/CORTX-S3 Server Quick Start Guide.md
-----
[View rendered docs/CORTX-S3 Server Quick Start Guide.md](https://github.com/Seagate/cortx-s3server/blob/br/pranav/EOS-18516/docs/CORTX-S3 Server Quick Start Guide.md)
> EOS-18516 : Updated Cortx-S3server quickstart guide

- server/s3_motr_writer.h
- server/s3_put_object_action.cc
- server/s3_put_object_action.h
- ut/s3_put_object_action_test.cc
- Changes in UT code: Fixed existing UTs and added new UTs
- Moderately changed S3 PUT object action class to accommodate UT changes.
> EOS-17325: Fix S3 UT/ST due to changes in EOS-17323

- s3backgrounddelete/s3backgrounddelete/object_recovery_msgbus.py
- s3cortxutils/s3msgbus/s3msgbus/cortx_s3_msgbus.py
1. S3msgbus changed to pseudo singleton.
2. Non Daemon mode exit position changed as it was going in infinite loop.
Premerge Job with msgbus : http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Component-Test/job/S3Server-PreMerge-Test/376/console
> [EOS-18602] ST's Failing when py-utils upgraded from v130 to v174

- ansible/files/yum.repos.d/centos7.7.1908/cortx.repo
- ansible/files/yum.repos.d/centos7.8.2003/cortx.repo
Signed-off-by: Gowthaman Chinnathambi <gowthaman.chinnathambi@seagate.com>
ISSUE: Main branch Build URL's are pointing to outdated old paths
FIX: Updated latest main build path
> EOS-18735 : Updated main branch Build locations

- scripts/kafka/create-topic.sh
- scripts/kafka/install-kafka.sh
- scripts/kafka/readme
- Fixed kafka installation for 3 node cluster
- added few helping command for kafka
> EOS-18668:S3: Fixed install kafka for 3 node cluster

- scripts/provisioning/cleanupcmd.py
Signed-off-by: pranav <pranav.pawar@seagate.com>
> EOS-18719:Erase haproxy configurations in cleanup phase

- docs/CORTX-S3 Server Quick Start Guide.md
epel check required
-----
[View rendered docs/CORTX-S3 Server Quick Start Guide.md](https://github.com/Seagate/cortx-s3server/blob/sachitanands-patch-1/docs/CORTX-S3 Server Quick Start Guide.md)
> Update CORTX-S3 Server Quick Start Guide.md (GitHub cortx - 836)

- scripts/ldap/ldapaccountaction.py
- scripts/provisioning/cleanupcmd.py
this check is added in Cleanup phase as pre-validation of reset phase is done or not.
> EOS-18717:[ Mini-Provisioner :S3: cleanup phase] Validate reset phase is done or not.

- ansible/files/yum.repos.d/centos7.8.2003/cortx_py_utils.repo
- scripts/env/common/setup-yum-repos.sh
- scripts/env/dev/init.sh
- scripts/env/release/init.sh
- scripts/env/rpmbuild/init.sh
- Shifted cortx-py-utils installation after motr 
- Added /usr/local/bin to environment variable
- removed all cortx repos before configuring again
> EOS-18889: Init script failure on fresh vm with latest cortx-py-utils

- scripts/provisioning/cleanupcmd.py
- scripts/provisioning/resetcmd.py
- scripts/provisioning/s3_setup
- scripts/provisioning/setupcmd.py
Shutdown s3 services during reset phase
> EOS-18598: Shutdown S3 services, during reset phase

- ansible/files/yum.repos.d/centos7.7.1908/cortx.repo
- ansible/files/yum.repos.d/centos7.8.2003/cortx.repo
Signed-off-by: Gowthaman Chinnathambi <gowthaman.chinnathambi@seagate.com>
> [Porting] EOS-18735 : Updated branch Build locations (#757)

- s3backgrounddelete/s3backgrounddelete/config/s3_background_delete_config.yaml.sample
> EOS-17213: Migrate to message_bus as default setting

- installhelper.sh
- rpms/s3/s3rpm.spec
- scripts/provisioning/configcmd.py
- scripts/provisioning/resetcmd.py
- scripts/provisioning/setupcmd.py
1)Added place holder for HA services command to start and stop s3 services 
2) used restart_services() function wherever applicable 
3) Remove s3prov_start_services.sh from RPM
Unit test is in progress.
> EOS-18891: Restart of services in all phases (except config) phase of mini provisioner

- server/s3_put_object_action.cc
- server/s3_put_object_action.h
- ut/s3_put_object_action_test.cc
> EOS-17355: [Fault tolerance:] S3 Put object API : Support for Rollback and Cleanup

- scripts/env/dev/init.sh
> [EOS-19148]Installation Step for intel ISA (motr dependency)

- scripts/env/dev/init.sh
> Installation Step for intel ISA - 2

- st/clitests/awss3api.py
- st/clitests/fault_tolerence_spec.py
- st/clitests/framework.py
- st/clitests/s3kvs.py
This spec file is developed for the new S3 fault tolerance feature.
Currently, added tests:
1. To create a fragmented object in Motr store using S3 FI
2. To validate the S3 metadata of fragmented object (e.g. FNo, list fragments)
3. To download fragmented object using aws s3api and verify that MD5 hash of uploaded and downloaded files match.
> EOS-18612: Standalone ST for S3 Fault tolerance feature

- s3cortxutils/s3confstore/ut/s3confstore_unit_tests.py
- Removed the mocked unit tests
- added system test for delete and copy.
-
> EOS-19148: Fixed the confstore unit test and converted in to system test

- server/s3_object_metadata.h
- server/s3_post_multipartobject_action.h
- st/clitests/framework.py
- st/clitests/jclient_spec.py
- ut/s3_object_metadata_test.cc
- ut/s3_post_multipartobject_action_test.cc
> EOS-17357 : Initiate multipart STs and UTs

- scripts/provisioning/setup.yaml
> [EOS-19369] Removing plan from setup.yaml as provisioner guideline

- server/s3_addb_map_auto.c
- server/s3_part_metadata.cc
- server/s3_part_metadata.h
- server/s3_probable_delete_record.cc
- server/s3_put_multiobject_action.cc
- server/s3_put_multiobject_action.h
- ut/s3_object_api_handler_test.cc
- ut/s3_object_metadata_test.cc
- ut/s3_post_multipartobject_action_test.cc
- ut/s3_put_multiobject_action_test.cc
Part upload will result in creation of new OID,
background to take care of stale OIDs, saving
of new OID to part table
> [EOS-17279]Multipart Part uploads as per new design

- s3config.release.yaml.sample
- s3config.yaml.sample
- server/s3_delete_object_action.cc
- server/s3_delete_object_action.h
- server/s3_object_metadata.cc
- server/s3_object_metadata.h
- server/s3_put_object_action.cc
- st/clitests/fault_tolerence_spec.py
- st/clitests/s3kvs.py
- ut/s3_delete_object_action_test.cc
Note: Existing UT and ST are successful.
> EOS-17303: S3faulttolerence - Object Del (single object) API support

- scripts/provisioning/cleanupcmd.py
- scripts/provisioning/configcmd.py
- scripts/provisioning/initcmd.py
- scripts/provisioning/postinstallcmd.py
- scripts/provisioning/preparecmd.py
- scripts/provisioning/resetcmd.py
- scripts/provisioning/s3_prov_config.yaml
- scripts/provisioning/s3_setup
- scripts/provisioning/setupcmd.py
- scripts/provisioning/testcmd.py
Validate keys extracted from template files against confstore keys
Files modified :
scripts/provisioning/postinstallcmd.py
Testing :
In progress.
> EOS-18824 : Validate keys extracted for each phase from each phase of provisioning

- server/s3_addb_map_auto.c
- server/s3_bucket_metadata.cc
- server/s3_bucket_metadata.h
- server/s3_bucket_metadata_v1.cc
- server/s3_bucket_metadata_v1.h
- server/s3_delete_bucket_action.cc
- server/s3_delete_bucket_action.h
- st/clitests/negative_spec.py
- ut/s3_bucket_metadata_v1_test.cc
Extended metadata index creation during bucket
creation and deletion
> EOS-19192: Extended metadata index creation

- server/s3_bucket_metadata_cache.cc
- server/s3_bucket_metadata_cache.h
- server/s3_bucket_metadata_proxy.cc
- server/s3_put_fi_action.cc
- ut/s3_bucket_metadata_cache_test.cc
> EOS-18207: bucket metadata cache - part 2

- auth/server/src/main/java/com/seagates3/dao/ldap/AccountImpl.java
> EOS-17244 Fixed code formatting issue

- installhelper.sh
- rpms/s3/s3rpm.spec
- scripts/ldap/replication/setupReplicationScript.sh
> EOS-19597: 's3_setup config' fails in 3 node miniprovisioner setup due to LDAP replication idempotency failure

- scripts/ldap/setup_ldap.sh
- scripts/provisioning/cleanupcmd.py
> EOS-19156: 's3_setup config' fails in 3 node miniprovisioner setup

- docs/s3-supported-api.md
-----
[View rendered docs/s3-supported-api.md](https://github.com/Seagate/cortx-s3server/blob/br/ak/EOS-19587-add-copyobject-to-supported-apis/docs/s3-supported-api.md)
> EOS:19587 - Add CopyObject API as supported API in the APIs Document.

- s3backgrounddelete/s3backgrounddelete/object_recovery_msgbus.py
- s3cortxutils/s3msgbus/s3msgbus/cortx_s3_msgbus.py
- s3cortxutils/s3msgbus/s3msgbus/s3msgbus
- scripts/provisioning/cleanupcmd.py
- scripts/provisioning/configcmd.py
- scripts/provisioning/resetcmd.py
_[EOS-19063](https://jts.seagate.com/browse/EOS-19063):_
_Cleanup of message bus object._
- remove message bus object creation
- remove connect method to msgbus
- remove reconnect logic to msgbus
- Run background delete ST on dev VM
<details>
<summary>Output of UT  </summary>
[root@ssc-vm-3160 cortx-s3server]# python36 st/clitests/backgrounddelete_spec.py
Configuring LDAP
adding new entry "ou=accounts,dc=s3,dc=seagate,dc=com"
adding new entry "ou=accesskeys,dc=s3,dc=seagate,dc=com"
adding new entry "ou=idp,dc=s3,dc=seagate,dc=com"
adding new entry "o=s3_test,ou=accounts,dc=s3,dc=seagate,dc=com"
adding new entry "ou=users,o=s3_test,ou=accounts,dc=s3,dc=seagate,dc=com"
adding new entry "ou=roles,o=s3_test,ou=accounts,dc=s3,dc=seagate,dc=com"
adding new entry …
> EOS-19063: [I&P] [MsgBus] Cleanup of message bus object

- third_party/build_motr.sh
> EOS-19672: Update git commit hash of motr in s3server repository.

- server/s3_copy_object_action.cc
> EOS-19623: Copy object test: ETag mismatch in put & copy object operation

- server/s3_get_bucket_action.cc
- server/s3_get_bucket_action.h
- server/s3_motr_kvs_reader.cc
In case if motr returns E2BIG, s3 handling of it
> EOS-19529: S3 handling of E2BIG

- docs/s3-supported-api.md
-----
[View rendered docs/s3-supported-api.md](https://github.com/Seagate/cortx-s3server/blob/br/ak/EOS-20340-update-s3API-doc/docs/s3-supported-api.md)
> EOS:20340 Update S3 API document with Multipart upload limitation.

- scripts/env/dev/init.sh
- scripts/env/release/init.sh
- scripts/env/rpmbuild/init.sh
increase sleep count from 5 to 30 for kafka service to up and running
> EOS-18812: increase sleep count from 5 to 30 for kafka service to up and running 

- auth/server/src/main/java/com/seagates3/authserver/AuthServerConfig.java
- scripts/enc_ldap_passwd_in_cfg.sh
- scripts/install_prereqs.sh
- scripts/s3-support-bundles/s3_bundle_generate.sh
link to known issue: https://bugs.python.org/issue9334
> EOS-20539: Fix argparse known issue to except dash('-') in option value.

- docs/s3-supported-api.md
-----
[View rendered docs/s3-supported-api.md](https://github.com/Seagate/cortx-s3server/blob/br/ak/fix-s3apis-doc/docs/s3-supported-api.md)
> Fixed s3iamcli usage in the API document.

- server/s3_get_object_action.cc
- server/s3_motr_reader.cc
- server/s3_object_data_copier.cc
- server/s3_object_data_copier.h
- Fix for range read related test case failures
> EOS-20315: Fix for Ceph/Splunk test case failures

- auth/server/src/main/java/com/seagates3/controller/AccountLoginProfileController.java
- auth/server/src/main/java/com/seagates3/controller/IAMController.java
- auth/server/src/test/java/com/seagates3/controller/AccountLoginProfileControllerTest.java
Update Account Login Profile using LDAP credentials shows inappropriate Auth Logs .
> [EOS-20542,EOS-20544,EOS-20554,EOS-20561] : Updates and fixes in Account Login Profile 

- scripts/ldap/ldapaccountaction.py
- scripts/provisioning/cleanupcmd.py
- scripts/provisioning/configcmd.py
- scripts/provisioning/initcmd.py
- scripts/provisioning/postinstallcmd.py
- scripts/provisioning/preparecmd.py
- scripts/provisioning/resetcmd.py
- scripts/provisioning/s3_haproxy_config.py
- scripts/provisioning/s3_setup
- scripts/provisioning/setupcmd.py
- scripts/provisioning/testcmd.py
- scripts/s3-support-bundles/s3_bundle_generate.sh
> [EOS-17842] Adding Logger framework in s3 mini provisioner

- scripts/env/common/configure_lnet.sh
- scripts/env/dev/init.sh
- scripts/env/release/init.sh
- scripts/env/rpmbuild/init.sh
Remove easy_install pip command from opensource init.sh script for dev vm.
> GitIssue-881: remove pip installtion through easy_install and add lnet validator

- server/s3_iem.h
- server/s3_log.h
> [EOS-20691] Add tz info into DI iem msg

- scripts/Compatibilty-test/CephSplunkCommitinfo
Signed-off-by: Shazia Ahmad <Shazia.Ahmad@seagate.com>
> Updated comments with ceph and splunk commits

- auth/encryptcli/pom.xml
- auth/server/pom.xml
> [EOS-19908] : Bumping up the commons validator version

- docs/CORTX-S3 Server Quick Start Guide.md
I edited the text for hostname to make it more understandable.
Signed-off-by: Justin Woo <justin.woo@seagate.com>
-----
[View rendered docs/CORTX-S3 Server Quick Start Guide.md](https://github.com/justinzw/cortx-s3server/blob/patch-2/docs/CORTX-S3 Server Quick Start Guide.md)
> Update CORTX-S3 Server Quick Start Guide.md

- CODEOWNERS
AjinkyaDhumal is being removed as CODEOWNER -
> Remove CODEOWNER

- st/clitests/awss3api.py
- st/clitests/awss3api_spec.py
Signed-off-by: root <root@ssc-vm-4852.colo.seagate.com>
> EOS-20528 : S3 Copy objects STs to verify the sanity of the objects.

- s3config-test.yaml
- server/s3_evbuffer_wrapper.cc
- server/s3_motr_context.cc
- server/s3_motr_reader.cc
- server/s3_motr_reader.h
- server/s3_motr_writer.h
- ut/s3_motr_writer_test.cc
- ut/s3_option_test.cc
Passing all UT's when read and write flags are off.
> [EOS-19713] STs and UTs for DI

- scripts/ldap/setup_ldap.sh
Remove selinux related commands from setup_ldap.sh 
> [OVA-issue]:S3:Remove setenforce comamnd from setup_ldap.sh

- scripts/s3-sanity/s3-sanity-test.sh
> [EOS-19644] Add s3 sanity tests for different CORTX versions.

- scripts/env/dev/init.sh
- scripts/env/release/init.sh
- scripts/env/rpmbuild/init.sh
Fixed the renamed of files from py-utils.
> EOS-21137: Fixed the py-utils dependencies

- .gitignore
- scripts/env/dev/init.sh
- scripts/env/release/init.sh
- scripts/env/rpmbuild/init.sh
> EOS-21137: Removed python numpy 1.19.5 package

- .gitignore
- scripts/env/dev/init.sh
- scripts/env/release/init.sh
- scripts/env/rpmbuild/init.sh
> EOS-21137: removed --ignore-installed flag.

- docs/R2-setup/Haproxy 3 Node load balancing.md
- docs/object-protection-testing.md
- s3config.release.yaml.sample
- s3config.yaml.sample
- scripts/haproxy/haproxy_osver7.cfg
- scripts/haproxy/haproxy_osver8.cfg
- scripts/provisioning/s3_haproxy_config.py
-----
[View rendered docs/R2-setup/Haproxy 3 Node load balancing.md](https://github.com/Seagate/cortx-s3server/blob/br/ng/EOS-21010/docs/R2-setup/Haproxy 3 Node load balancing.md)
[View rendered docs/object-protection-testing.md](https://github.com/Seagate/cortx-s3server/blob/br/ng/EOS-21010/docs/object-protection-testing.md)
> [EOS-21010] Changing port to 28071

- auth-utils/jclient/pom.xml
- auth-utils/jcloudclient/pom.xml
1) logback-classic-1.0.13.jar - https://github.com/Seagate/cortx-s3server/issues/556 (jcloud)
2) log4j-1.2.17.jar -https://github.com/Seagate/cortx-s3server/issues/573 (jclient)
3) aws-java-sdk-s3-1.11.37.jar (Needs upgrade) - Jclient
below is versions to be upgraded,
1) aws-java-sdk-s3  1.11.37 -> 1.12.2
2) aws-java-sdk-iam 1.11.37 -> 1.12.2
3) log4j-core   2.14.0 -> 2.14.1
4) logback-classic 1.0.13 -> 1.2.3
> EOS-19860:system test package vulnerability fixes

- ut/s3_motr_reader_test.cc
- ut/s3_option_test.cc
> [EOS-19713] Pass UT with Data Integrity for read enabled. 

- server/s3_put_object_action.cc
"Put object with object tagging is working without Access for PutobjectTagging from cross-account."
> [EOS-20830] : Put object with object tagging is working without Access for PutobjectTagging from cross-account.

- server/s3_post_complete_action.cc
- server/s3_post_complete_action.h
> [EOS-21134] Fix order parts' etags concatenated - make it explicit in order of parts

- scripts/provisioning/cleanupcmd.py
- scripts/provisioning/s3_setup
In clean up phase , revert config files when we do "--pre-factory" flag is passed
> EOS-19676:S3: revert config files when --pre_factory flag is passed

- server/s3_object_data_copier.cc
- server/s3_object_data_copier.h
- ut/mock_s3_motr_reader.h
- ut/s3_object_data_copier_test.cc
> EOS-21324: copy-object causes s3server crash

- .whitesource
> Update .whitesource file

- whitesource.config
Added whitesource config file for exclude rules
> Added whitesource config file

- s3backgrounddelete/s3backgrounddelete/IEMutil.py
- s3backgrounddelete/s3backgrounddelete/cortx_s3_count_kv.py
- s3backgrounddelete/ut/cortx_s3_iem_tests.py
> [EOS-19647] : BG Services Integration with IEM framework infrastructure

- server/s3_copy_object_action.cc
Reverts Seagate/cortx-s3server#1010
> Revert "EOS-20766 ReFix CopyObject not checking GetObjectTagging permission"

- server/action_base.cc
- server/s3_action_base.cc
- server/s3_post_complete_action.cc
> EOS-22012: Fix to some of the invalid reads leading to crash

- scripts/ldap/create_account_using_cipher.py
- st/clitests/s3_background_delete_config_test.yaml
> [EOS-19172] : Refactoring of backgrounddelete account creation process-ST changes

- s3backgrounddelete/s3backgrounddelete/cortx_s3_object_api.py
- s3backgrounddelete/s3backgrounddelete/object_recovery_validator.py
- s3backgrounddelete/ut/cortx_s3_object_api_tests.py
- s3backgrounddelete/ut/object_recovery_validator_tests.py
- server/motr_delete_object_action.cc
- server/motr_delete_object_action.h
- server/s3_abort_multipart_action.cc
- server/s3_delete_multiple_objects_action.cc
- server/s3_delete_object_action.cc
- server/s3_post_complete_action.cc
- server/s3_probable_delete_record.cc
- server/s3_probable_delete_record.h
- server/s3_put_chunk_upload_object_action.cc
- server/s3_put_object_action.cc
- server/s3_put_object_action_base.cc
- third_party/build_motr.sh
- ut/mock_s3_probable_delete_record.h
- ut/s3_abort_multipart_test.cc
- ut/s3_copy_object_action_test.cc
- ut/s3_delete_multiple_objects_action_test.cc
- ut/s3_post_complete_action_test.cc
- ut/s3_put_chunk_upload_object_action_test.cc
- ut/s3_put_object_action_test.cc
Testing Done :
> [root@ssc-vm-1453 cortx-s3server]# s3cmd put abc.txt s3://deepakbucket
> upload: 'abc.txt' -> 's3://deepakbucket/abc.txt'  [1 of 1]
>  4099 of 4099   100% in    0s     3.13 MB/smotr[129446]:  b9f0  ERROR  [cas/service.c:1262:cas_fom_tick]  <! rc=-2
> motr[130100]:  a180  ERROR  [cas/client.c:1172:cas_req_replied_ast]  <! rc=-2
>  4099 of 4099   100% in    6s   613.70 B/s  done
> [root@ssc-vm-1453 cortx-s3server]# s3cmd put abc.txt s3://deepakbucket
> upload: 'abc.txt' -> 's3://deepakbucket/abc.txt'  [1 of 1]
>  4099 of 4099   100% in    4s   874.23 B/s  done
>[root@ssc-vm-1453 cortx-s3server]# ./s3backgrounddelete/scripts/list_kv.py "AAAAAAAAAHg=-AwAQAAAAAAA="
{'Delimiter': '', 'Index-Id': 'AAAAAAAAAHg=-AwAQAAAAAAA=', 'IsTruncated': 'false', 'Keys': [{'Key': …
> [ EOS-21376, EOS-21169 ] C++ and Python Changes for probable delete index to include PVID and layout id.

- server/s3_md5_hash.cc
- server/s3_motr_writer.cc
> [EOS-22852] Multipart upload failures for 5M+2k parts

- server/s3_get_object_action.cc
> EOS-23035: Fix to data send to client for each fragment

- ansible/files/yum.repos.d/centos7.9.2009/cortx.repo
- ansible/files/yum.repos.d/centos7.9.2009/cortx_s3_deps.repo
> [EOS-22158] : Migration to CentOS 7.9 - Part 2

- .github/workflows/alex_reviewdog.yml
- jenkins-build.sh
- rebuildall.sh
- scripts/kafka/install-kafka.sh
1) Enable option to specify ram and cpu usage for bazel during jenkins-build.sh script
2) Fix issue with install-kafka script
> EOS-18521:Bazel enhancements and kafka script modification

- scripts/provisioning/configcmd.py
- scripts/provisioning/templates/s3.config.tmpl.1-node
- scripts/provisioning/templates/s3.config.tmpl.1-node.sample
- scripts/provisioning/templates/s3.config.tmpl.3-node
- scripts/provisioning/templates/s3.config.tmpl.3-node.sample
- scripts/provisioning/templates/s3.init.tmpl.1-node
- scripts/provisioning/templates/s3.init.tmpl.1-node.sample
Signe-off-by: Vimal Raghwani <vimal.raghwani@seagate.com>
> EOS-19912: Fixed the motr max request config param from template files

- scripts/provisioning/templates/s3.config.tmpl.3-node
- scripts/provisioning/templates/s3.config.tmpl.3-node.sample
- scripts/provisioning/templates/s3.init.tmpl.1-node
- scripts/provisioning/templates/s3.init.tmpl.1-node.sample
> EOS-19912: Fixed instance count in to all config files

- server/s3_object_metadata.cc
> [EOS-22885] : Multipart redesign: Missing version key from the listing of extended entries

- server/s3_motr_writer.cc
- server/s3_motr_writer.h
> Minor DI Fixes

- server/s3_get_object_action.cc
> [EOS-23253] Fixed first_blocks_to_read calculation

- server/s3_evbuffer_wrapper.cc
- server/s3_motr_context.cc
- server/s3_motr_reader.h
> [EOS-22175] Added logs to see which memory allocation failed

- .whitesource
Update whitesource to retrigger scan
> Update whitesource to retrigger scan

- whitesource.config
Update whitesource.config to add package manager parameter
> Update whitesource.config to add package manager parameter

- .github/pull_request_template.md
-----
[View rendered .github/pull_request_template.md](https://github.com/Seagate/cortx-s3server/blob/br/vr/PR_template/.github/pull_request_template.md)
> Pull request template 

- third_party/build_motr.sh
- Uses Motr commit f742ffad17425574d7c05e8063be242c04d6c91a (as on 6th Aug 2021, 1PM IST)
- Need to integrate latest Motr changes in S3 server to support pv id/layout type
changes in Motr.
> EOS-22190: Integrate latest Motr in S3 server for pv id/layout type changes

- scripts/coverage/python_coverage.sh
> Remove duplicate run_ut() from python_coverage.sh

- auth/resources/authserver.properties.sample
- auth/server/src/main/java/com/seagates3/authserver/AuthServerConfig.java
- auth/server/src/main/java/com/seagates3/controller/IAMController.java
- auth/server/src/main/java/com/seagates3/model/AuthIAMAuditlog.java
- auth/server/src/main/java/com/seagates3/s3service/AuditLogRestClient.java
- scripts/rsyslog-tcp-audit.conf
- Overview: JIRA number/GitHub Issue added to PR: [Y/N]:
-  For Bug describe the fix here.
-  For Feature, Post the link to the solution page on the confluence CORTX Foundation Library
-  Coding conventions are followed and code is consistent [Y/N]:
- Unit and System Tests are added [Y/N]:
- Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]:
- Testing was performed with RPM [Y/N]:
Before Merging the PR please ensure
- Interface change (if any) are documented [Y/N]:
- Side effects on other features (deployment/upgrade) [Y/N]:
- Changes to quick-start-guide/community impact [Y/N]:
- Dependencies on other component(s) [Y/N]:
Before posting the PR please ensure
> EOS-22322: IAM Audit log implementation 

- auth/server/src/main/java/com/seagates3/controller/IAMController.java
- auth/server/src/main/java/com/seagates3/model/AuthIAMAuditlog.java
- auth/server/src/main/java/com/seagates3/s3service/AuditLogRestClient.java
> Code format fixed

- server/s3_get_object_action.h
- server/s3_post_complete_action.h
- ut/s3_get_object_action_test.cc
- ut/s3_post_complete_action_test.cc
- Develop new uts for get object api.
> [EOS-23321] : Develop new UTs for Get Object APi

- scripts/provisioning/cleanupcmd.py
- scripts/provisioning/configcmd.py
- scripts/provisioning/initcmd.py
- scripts/provisioning/postinstallcmd.py
- scripts/provisioning/postupgradecmd.py
- scripts/provisioning/preparecmd.py
- scripts/provisioning/preupgradecmd.py
- scripts/provisioning/resetcmd.py
- scripts/provisioning/s3_setup
- scripts/provisioning/setupcmd.py
- scripts/provisioning/testcmd.py
- Add module name parameter to mini provisioner framework
-  Added module name parameter to mini provisioner framework
> EOS-23396: [k8s] Added module name parameter to mini provisioner framework

- installhelper.sh
- rpms/s3/s3rpm.spec
- scripts/provisioning/setup.yaml
- scripts/provisioning/support.yaml
Support bundle yaml file seperation for provisioner
Support bundle yaml file seperation for provisioner
> Support bundle yaml file seperation for provisioner

- server/s3_delete_object_action.cc
Fixing multiple issues reported in EOS-20051 bug
> EOS-20051:S3: Log level fix

- server/s3server.cc
> Rebasing node_stop

- server/s3_md5_hash.cc
- server/s3_motr_context.cc
> Code Formatting Changes in dataIntegrity.

- .github/workflows/alex_reviewdog.yml
Signed-off-by: Venkatesh K <venkatesh.k@seagate.com>
> Change in Alex event trigger

- docs/CORTX-S3 Server Quick Start Guide.md
Signed-off-by: Patrick Hession <patrick.hession@seagate.com>
Closes #1006 
- Added myself to the 'tested by' section as I was able to get this up and running today.
- Tested with bare metal server
- Tested with VMWare Workstation Pro 16
-----
[View rendered docs/CORTX-S3 Server Quick Start Guide.md](https://github.com/Seagate/cortx-s3server/blob/hessio-patch-1/docs/CORTX-S3 Server Quick Start Guide.md)
> Added myself to 'tested by' section

- server/s3_motr_reader.cc
> DI Enabled Change

- s3config-test.yaml
- s3config.release.yaml.sample
- s3config.yaml.sample
- server/motr_common.cc
- server/s3_option.cc
- server/s3_option.h
- server/s3server.cc
> EOS-23400 Startup dependency removal of s3server (Motr only.)

- auth/server/src/test/java/com/seagates3/authserver/AuthServerConfigTest.java
- auth/server/src/test/java/com/seagates3/perf/S3PerfTest.java
Code check format fix on K8S branch
-----
[View rendered docs/notes.md](https://github.com/Seagate/cortx-s3server/blob/br/vr/k8s-codeformat-fix/docs/notes.md)
[View rendered s3backgrounddelete/readme.md](https://github.com/Seagate/cortx-s3server/blob/br/vr/k8s-codeformat-fix/s3backgrounddelete/readme.md)
[View rendered scripts/formatcheckers/readme.md](https://github.com/Seagate/cortx-s3server/blob/br/vr/k8s-codeformat-fix/scripts/formatcheckers/readme.md)
> [K8S] Code check format fix on K8S branch

- auth/server/src/test/java/com/seagates3/authserver/AuthServerConfigTest.java
- jenkins-build.sh
- Changes for Pre-Merge in K8S branch
> EOS-23396: Changes for Pre-Merge in K8S branch

- scripts/provisioning/configcmd.py
- scripts/provisioning/setupcmd.py
Changing the function call from get_confvalue() to get_confvalue_with_defaults()
> K8s changes to adhere with latest function.

- scripts/provisioning/cleanupcmd.py
- scripts/provisioning/configcmd.py
- scripts/provisioning/resetcmd.py
- scripts/provisioning/s3_haproxy_config.py
- scripts/provisioning/s3_setup
- scripts/provisioning/setupcmd.py
> [EOS-24037] : [K8s] Generate log directories based on container id for s3 component (P2)

- scripts/provisioning/configcmd.py
- scripts/provisioning/s3_setup
> Flag rename changes

- scripts/provisioning/templates/s3.config.tmpl.1-node
- scripts/provisioning/templates/s3.config.tmpl.1-node.sample
- scripts/provisioning/templates/s3.config.tmpl.3-node
- scripts/provisioning/templates/s3.config.tmpl.3-node.sample
-----
[View rendered docs/notes.md](https://github.com/Seagate/cortx-s3server/blob/br/pranav/new/config-changes/docs/notes.md)
[View rendered s3backgrounddelete/readme.md](https://github.com/Seagate/cortx-s3server/blob/br/pranav/new/config-changes/s3backgrounddelete/readme.md)
> Updating config file to latest

- scripts/provisioning/configcmd.py
-----
[View rendered docs/notes.md](https://github.com/Seagate/cortx-s3server/blob/br/it/EOS-24042/docs/notes.md)
[View rendered s3backgrounddelete/readme.md](https://github.com/Seagate/cortx-s3server/blob/br/it/EOS-24042/s3backgrounddelete/readme.md)
> EOS-24042: add convertor functions for bg delete port, and auth host and ports

- scripts/provisioning/templates/s3.config.tmpl.1-node
- scripts/provisioning/templates/s3.config.tmpl.1-node.sample
- scripts/provisioning/templates/s3.config.tmpl.3-node
- scripts/provisioning/templates/s3.config.tmpl.3-node.sample
-----
[View rendered docs/notes.md](https://github.com/Seagate/cortx-s3server/blob/br/pranav/new-config-changes/docs/notes.md)
[View rendered s3backgrounddelete/readme.md](https://github.com/Seagate/cortx-s3server/blob/br/pranav/new-config-changes/s3backgrounddelete/readme.md)
> New config changes

- scripts/provisioning/configcmd.py
- scripts/provisioning/setupcmd.py
- scripts/provisioning/templates/s3.config.tmpl.1-node
- scripts/provisioning/templates/s3.config.tmpl.1-node.sample
- scripts/provisioning/templates/s3.config.tmpl.3-node
- scripts/provisioning/templates/s3.config.tmpl.3-node.sample
> [EOS-24361] : Mini prov Fix

- scripts/provisioning/configcmd.py
> EOS-24042: confstore: more fixes and address review comments

- scripts/provisioning/configcmd.py
- scripts/provisioning/templates/s3.config.tmpl.1-node
- scripts/provisioning/templates/s3.config.tmpl.1-node.sample
- scripts/provisioning/templates/s3.config.tmpl.3-node
- scripts/provisioning/templates/s3.config.tmpl.3-node.sample
> Mini prov fix.

- scripts/provisioning/configcmd.py
- scripts/provisioning/s3_haproxy_config.py
- scripts/provisioning/templates/s3.config.tmpl.1-node
- scripts/provisioning/templates/s3.config.tmpl.1-node.sample
- scripts/provisioning/templates/s3.config.tmpl.3-node
- scripts/provisioning/templates/s3.config.tmpl.3-node.sample
- scripts/provisioning/templates/s3.init.tmpl.1-node
- scripts/provisioning/templates/s3.init.tmpl.1-node.sample
> Init template file changes

- scripts/provisioning/configcmd.py
- scripts/provisioning/s3_haproxy_config.py
- scripts/provisioning/s3_prov_config.yaml
- scripts/provisioning/setupcmd.py
- scripts/provisioning/templates/s3.config.tmpl.1-node
- scripts/provisioning/templates/s3.config.tmpl.1-node.sample
- scripts/provisioning/templates/s3.config.tmpl.3-node
- scripts/provisioning/templates/s3.config.tmpl.3-node.sample
- scripts/provisioning/templates/s3.init.tmpl.1-node
- scripts/provisioning/templates/s3.init.tmpl.1-node.sample
1) Adding new confstore keys (Public and Private keys) 
2) Separation of mandatory and optional parameters with their default value 
> EOS-24042:S3: Mapping of new provisioner confstore keys to s3 confstore keys for K8S

- installhelper.sh
- rpms/s3/s3rpm.spec
- scripts/provisioning/s3_haproxy_config.py
- scripts/provisioning/s3_start
- scripts/provisioning/starthaproxy.sh
- Haproxy micro-provisioner implementation
-  As per design, this service has to take care of filling out the config file and starting haproxy.
> EOS-24655 - Kubernetes haproxy micro-provisioner code changes.

- scripts/provisioning/templates/s3.post_install.tmpl.1-node
- scripts/provisioning/templates/s3.post_install.tmpl.1-node.sample
- scripts/provisioning/templates/s3.prepare.tmpl.1-node
- scripts/provisioning/templates/s3.prepare.tmpl.1-node.sample
- scripts/provisioning/templates/s3.test.tmpl.1-node
- scripts/provisioning/templates/s3.test.tmpl.1-node.sample
> Added setup type to prepare and post install phase.

- scripts/provisioning/templates/s3.post_install.tmpl.1-node
- scripts/provisioning/templates/s3.post_install.tmpl.1-node.sample
- scripts/provisioning/templates/s3.prepare.tmpl.1-node
- scripts/provisioning/templates/s3.prepare.tmpl.1-node.sample
- scripts/provisioning/templates/s3.test.tmpl.1-node
- scripts/provisioning/templates/s3.test.tmpl.1-node.sample
> Added Setup type as K8 to all phases.

- scripts/provisioning/cleanupcmd.py
- scripts/provisioning/configcmd.py
- scripts/provisioning/initcmd.py
- scripts/provisioning/postinstallcmd.py
- scripts/provisioning/postupgradecmd.py
- scripts/provisioning/preparecmd.py
- scripts/provisioning/preupgradecmd.py
- scripts/provisioning/resetcmd.py
- scripts/provisioning/s3_setup
- scripts/provisioning/setupcmd.py
> EOS23401- Handling for --service parameter in s3 provisioning

- scripts/ldap/s3_setup_ldap.sh
- scripts/provisioning/configcmd.py
> Update authserver password in configcmd

- scripts/provisioning/s3_haproxy_config.py
- scripts/provisioning/templates/s3.config.tmpl.1-node
- scripts/provisioning/templates/s3.config.tmpl.1-node.sample
- scripts/provisioning/templates/s3.config.tmpl.3-node
- scripts/provisioning/templates/s3.config.tmpl.3-node.sample
- scripts/provisioning/templates/s3.init.tmpl.1-node
- scripts/provisioning/templates/s3.init.tmpl.1-node.sample
-----
[View rendered docs/notes.md](https://github.com/Seagate/cortx-s3server/blob/br/ms/ssl_cert_haproxy/docs/notes.md)
[View rendered s3backgrounddelete/readme.md](https://github.com/Seagate/cortx-s3server/blob/br/ms/ssl_cert_haproxy/s3backgrounddelete/readme.md)
> HAproxy port numbers should be read from confstore.

- scripts/ldap/s3_setup_ldap.sh
> Slapd password hash changes

- scripts/ldap/ldapaccountaction.py
- scripts/provisioning/configcmd.py
> Remove hardcoded ldaphost string from ldapaccountaction class

- auth/server/s3authserver.service
- scripts/ldap/ldapaccountaction.py
- scripts/provisioning/configcmd.py
- scripts/provisioning/s3_start
1) fix for startup script (https://github.com/Seagate/cortx-s3server/pull/1292/files) 
> K8: python fix for mini-provisioner issue

- scripts/provisioning/configcmd.py
> Left over fix on conf key change

- s3config-test.yaml
- s3config.release.yaml.sample
- s3config.yaml.sample
This reverts commit 568936989d314451f6d0d49fd3ee6713fdc4ef70.
> Revert "enable DI with latest Main branch (#1249)"

- scripts/provisioning/s3_start
- scripts/provisioning/starthaproxy.sh
> EOS-24974: specify proper path for BG consumer

- s3backgrounddelete/s3backgrounddelete/config/s3_background_delete_config.yaml.sample
- s3backgrounddelete/s3backgrounddelete/cortx_s3_config.py
- s3backgrounddelete/s3backgrounddelete/object_recovery_processor.py
- s3backgrounddelete/s3backgrounddelete/object_recovery_scheduler.py
- scripts/provisioning/configcmd.py
- scripts/provisioning/s3_haproxy_config.py
- scripts/provisioning/s3_prov_config.yaml
> Sagregated log dir for producer/consumer

- s3backgrounddelete/s3backgrounddelete/object_recovery_validator.py
- server/s3_post_complete_action.cc
- server/s3_put_object_action.cc
- server/s3_put_object_action.h
> [EOS-22168] Multipart object overwrite with Simple object (bgdelete handling)

- scripts/provisioning/configcmd.py
- scripts/provisioning/s3_start
- scripts/provisioning/starthaproxy.sh
> EOS-24974: Use machine-id in log path for haproxy log file

- s3backgrounddelete/s3backgrounddelete/object_recovery_processor.py
- s3backgrounddelete/s3backgrounddelete/object_recovery_scheduler.py
- scripts/provisioning/s3_setup
- scripts/provisioning/s3_start
> [EOS-25020] Fix for logger race 

- s3cortxutils/s3confstore/s3confstore/cortx_s3_confstore.py
- scripts/provisioning/configcmd.py
- scripts/provisioning/setupcmd.py
- scripts/provisioning/templates/s3.config.tmpl.1-node
- scripts/provisioning/templates/s3.config.tmpl.1-node.sample
- scripts/provisioning/templates/s3.config.tmpl.3-node
- scripts/provisioning/templates/s3.config.tmpl.3-node.sample
- scripts/provisioning/templates/s3.init.tmpl.1-node
- scripts/provisioning/templates/s3.init.tmpl.1-node.sample
- Template file array entries changed format
-  Format changed to align with provisioner
> Changes to template files to accomodate array entries in new format

- scripts/provisioning/s3_setup
- scripts/provisioning/templates/s3.cleanup.tmpl.1-node
- scripts/provisioning/templates/s3.cleanup.tmpl.1-node.sample
- scripts/provisioning/templates/s3.post_install.tmpl.1-node
- scripts/provisioning/templates/s3.post_install.tmpl.1-node.sample
- scripts/provisioning/templates/s3.prepare.tmpl.1-node
- scripts/provisioning/templates/s3.prepare.tmpl.1-node.sample
- scripts/provisioning/templates/s3.reset.tmpl.1-node
- scripts/provisioning/templates/s3.reset.tmpl.1-node.sample
- scripts/provisioning/templates/s3.test.tmpl.1-node
- scripts/provisioning/templates/s3.test.tmpl.1-node.sample
-----
[View rendered docs/notes.md](https://github.com/Seagate/cortx-s3server/blob/br/pranav/bug-fix/docs/notes.md)
[View rendered s3backgrounddelete/readme.md](https://github.com/Seagate/cortx-s3server/blob/br/pranav/bug-fix/s3backgrounddelete/readme.md)
> [MINI PROV] : Fixed deployment logger bug

- scripts/provisioning/configcmd.py
- scripts/provisioning/s3_prov_config.yaml
- scripts/provisioning/setupcmd.py
- scripts/provisioning/templates/s3.cleanup.tmpl.1-node
- scripts/provisioning/templates/s3.cleanup.tmpl.1-node.sample
- scripts/provisioning/templates/s3.config.tmpl.1-node
- scripts/provisioning/templates/s3.config.tmpl.1-node.sample
- scripts/provisioning/templates/s3.config.tmpl.3-node
- scripts/provisioning/templates/s3.config.tmpl.3-node.sample
- scripts/provisioning/templates/s3.init.tmpl.1-node
- scripts/provisioning/templates/s3.init.tmpl.1-node.sample
- scripts/provisioning/templates/s3.reset.tmpl.1-node
- scripts/provisioning/templates/s3.reset.tmpl.1-node.sample
> Changes to keys to align with confstore

- scripts/provisioning/templates/s3.config.tmpl.1-node
- scripts/provisioning/templates/s3.config.tmpl.1-node.sample
- scripts/provisioning/templates/s3.config.tmpl.3-node
- scripts/provisioning/templates/s3.config.tmpl.3-node.sample
- scripts/provisioning/templates/s3.init.tmpl.1-node
- scripts/provisioning/templates/s3.init.tmpl.1-node.sample
> Update default endpoints in s3 config tmpl

- server/s3_delete_bucket_action.cc
- ut/s3_delete_bucket_action_test.cc
> Rebase fix

- scripts/provisioning/configcmd.py
- scripts/provisioning/s3_prov_config.yaml
- scripts/provisioning/setupcmd.py
- scripts/provisioning/templates/s3.cleanup.tmpl.1-node
- scripts/provisioning/templates/s3.cleanup.tmpl.1-node.sample
- scripts/provisioning/templates/s3.config.tmpl.1-node
- scripts/provisioning/templates/s3.config.tmpl.1-node.sample
- scripts/provisioning/templates/s3.config.tmpl.3-node
- scripts/provisioning/templates/s3.config.tmpl.3-node.sample
- scripts/provisioning/templates/s3.init.tmpl.1-node
- scripts/provisioning/templates/s3.init.tmpl.1-node.sample
- scripts/provisioning/templates/s3.reset.tmpl.1-node
- scripts/provisioning/templates/s3.reset.tmpl.1-node.sample
> Fixes for Provisioner

- server/s3_common.h
- server/s3_copy_object_action.cc
- server/s3_get_object_action.cc
> Fix for unaligned read and sending of whitespace in case of multiple parts/fragments

- scripts/provisioning/s3_start
- scripts/provisioning/starthaproxy.sh
> Read path from confstore and remove hard-coding

- scripts/provisioning/configcmd.py
> Changes for softlink creation

- scripts/provisioning/configcmd.py
This reverts commit e34d0ebb365b1056f1413588fb7ed546eb5f7aaf.
> Revert "Changes for softlink creation (#1334)"

- scripts/provisioning/configcmd.py
> Softlink changes

- scripts/provisioning/configcmd.py
- scripts/provisioning/s3_prov_config.yaml
- scripts/provisioning/s3_start
tailf changes in s3_start script
tailf changes in s3_start script
> EOS-24396: tailf changes in s3_start script

- scripts/provisioning/s3_start
> S3_start fixes

- scripts/provisioning/s3_start
> fixed get_confkey()

- scripts/provisioning/s3_start
> Fixed the error in s3_setup

- scripts/provisioning/configcmd.py
- scripts/provisioning/s3_start
Add logging in service start
Added logging in service start
> EOS-24396: Added logging in service start

- scripts/env/kubernetes/k8s-blueprints/io-pod.yaml.template
- scripts/env/kubernetes/k8s-blueprints/s3-bg-producer-pod.yaml.template
- scripts/env/kubernetes/k8s-blueprints/s3-pv.yaml
- scripts/env/kubernetes/k8s-blueprints/shim-ctrl-pod.yaml.template
- scripts/env/kubernetes/k8s-blueprints/shim-pod.yaml.template
- scripts/env/kubernetes/message-bus/cortx.conf
- scripts/env/kubernetes/motr-hare/container-entry-point.sh
- scripts/env/kubernetes/sh/030-common-k8s-definitions.sh
- scripts/env/kubernetes/sh/042-create-solution-config.sh
- scripts/env/kubernetes/sh/043-prerequisites.sh
- scripts/env/kubernetes/sh/100-s3-client-setup.sh
- scripts/env/kubernetes/sh/120-confirm-bg-works.sh
Corresponding provisioner changes : https://github.com/sachitanands/cortx-prvsnr-Kubernetes/pull/4 
> [Draft ] K8- automation : changes for log location : /var/log -> /share/var/log

- server/s3_get_object_action.cc
> Fix for Get (splunk issue)

- server/s3_copy_object_action.h
- server/s3_object_data_copier.h
- st/clitests/awss3api_spec.py
- ut/s3_copy_object_action_test.cc
- ut/s3_object_data_copier_test.cc
> [EOS-22169] : {Multipart redesign} UTs and STs for S3 PUT Copy object API

- mempool/s3_memory_pool.c
- server/s3server.cc
Signed-off-by: Dattaprasad Govekar <dattaprasad.govekar@seagate.com>
> EOS-22175: Set additional  mempool logs at DEBUG level

- resources/s3_error_messages.json
- server/s3_addb_map_auto.c
- server/s3_addb_plugin_auto.cc
- server/s3_addb_plugin_auto.h
- server/s3_bucket_api_handler.cc
- server/s3_bucket_metadata.cc
- server/s3_bucket_metadata.h
- server/s3_factory.h
- server/s3_object_metadata.h
- server/s3_put_bucket_replication_action.cc
- server/s3_put_bucket_replication_action.h
- server/s3_put_replication_body.cc
- server/s3_put_replication_body.h
- ut/mock_s3_bucket_metadata.h
- ut/mock_s3_factory.h
- ut/mock_s3_object_metadata.h
- ut/mock_s3_put_replication_body.h
- ut/s3_put_bucket_replication_action_test.cc
- ut/s3_put_bucket_replication_body_test.cc
Signed-off-by: shraddhaghatol <shraddha.j.ghatol@seagate.com>
Implementation of Put-bucket-replication API
> EOS-24754 : Added Put-bucket-replication API related files

- scripts/env/kubernetes/config.sh.template
> New Symas Image

- server/s3_addb_map_auto.c
- server/s3_bucket_metadata.cc
- server/s3_bucket_metadata.h
- server/s3_object_metadata.h
- ut/mock_s3_bucket_metadata.h
- ut/mock_s3_object_metadata.h
- ut/s3_object_metadata_test.cc
- ut/s3_put_object_action_test.cc
Added unit test cases for upgradation of put_object APIs to support replication...
> [Replication]::EOS-25542 Added unit test cases for upgradation of put_object APIs to support replication..

- scripts/env/dev/init.sh
> EOS-25599:S3:install latest libfabric rpms for dev ansible scripts.

- st/clitests/awss3api_spec.py
> [EOS-25596] : Add ST for MP/copy/overwrite

- scripts/provisioning/s3_start
- scripts/s3-support-bundles/s3_bundle_generate.sh
> EOS-25442: Core dump fixes for kubernetes

- rpms/README.txt
- scripts/ssl/setup-ssl.sh
> EOS-17838:S3:SSL cert script changes with 10 years of expiry

- scripts/s3-logrotate/s3logfilerollover.sh
> EOS-25768:S3:enable cleanup of s3 core files during s3 log rotation

- docs/CORTX-S3 Server Quick Start Guide.md
1.  remove  from command lines as  referring non-root user but most commands need to be root to perform.
2. add -y to yum install command for install git.
Signed-off-by: Jalen Kan <jalen.j.kan@seagate.com>
-----
[View rendered docs/CORTX-S3 Server Quick Start Guide.md](https://github.com/jkan-cn/cortx-s3server/blob/jalen-patch1/docs/CORTX-S3 Server Quick Start Guide.md)
> Update docs/CORTX-S3 Server Quick Start Guide.md

- scripts/ldap/cn={1}s3user.ldif
IAM groups - Changes required in schema for openldap
- [IAM Group schema updates](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/790593850/OpenLDAP+Schema)
Signed-off-by: Shri Metta <shri.metta@seagate.com>
> EOS-25708: IAM Group schema update.

- auth/server/src/main/java/com/seagates3/controller/PolicyController.java
- auth/server/src/main/java/com/seagates3/dao/PolicyDAO.java
- auth/server/src/main/java/com/seagates3/dao/ldap/AuthStore.java
- auth/server/src/main/java/com/seagates3/dao/ldap/FileStore.java
- auth/server/src/main/java/com/seagates3/dao/ldap/LdapStore.java
- auth/server/src/main/java/com/seagates3/dao/ldap/MotrStore.java
- auth/server/src/main/java/com/seagates3/dao/ldap/PolicyImpl.java
- auth/server/src/main/java/com/seagates3/dao/ldap/PolicyLdapStore.java
- auth/server/src/test/java/com/seagates3/controller/PolicyControllerTest.java
- auth/server/src/test/java/com/seagates3/dao/ldap/FileStoreTest.java
- auth/server/src/test/java/com/seagates3/dao/ldap/LdapStoreTest.java
- st/clitests/awsiam.py
- st/clitests/awsiam_spec.py
- st/clitests/policy_files/iam-policy.json
PR created for refinement changes in policy CRUD code
> [IAM Policy] CRUD Refinement ,code fixes , UTs and STs

- third_party/build_motr.sh
> [EOS-25783] Advancing motr commit for libfab CPU fix

- scripts/provisioning/postupgradecmd.py
- scripts/provisioning/s3_setup
- scripts/swupdate/merge.py
> EOS-25798 : Fix preupgrade and postupgrade commands

- server/s3_common.h
- server/s3_post_complete_action.cc
- server/s3_put_chunk_upload_object_action.cc
- server/s3_put_multiobject_action.cc
- server/s3_put_object_action.cc
- server/s3_put_object_action.h
- ut/s3_post_complete_action_test.cc
- ut/s3_put_object_action_test.cc
> EOS-25891: Single PUT request to allow until 5GB

- auth/resources/authserver.properties.sample
- auth/server/src/main/java/com/seagates3/authserver/AuthServerConfig.java
- auth/server/src/main/java/com/seagates3/controller/PolicyController.java
- auth/server/src/main/java/com/seagates3/parameter/validator/S3ParameterValidatorUtil.java
- auth/server/src/main/java/com/seagates3/policy/BucketPolicyValidator.java
- auth/server/src/main/java/com/seagates3/policy/IAMArnParser.java
- auth/server/src/main/java/com/seagates3/policy/IAMPolicyValidator.java
- auth/server/src/main/java/com/seagates3/policy/PolicyValidator.java
- auth/server/src/main/java/com/seagates3/response/generator/PolicyResponseGenerator.java
- auth/server/src/test/java/com/seagates3/controller/PolicyControllerTest.java
- auth/server/src/test/java/com/seagates3/policy/IAMPolicyValidatorTest.java
- st/clitests/awsiam_spec.py
- st/clitests/policy_files/iam-policy-version-missing.json
- st/clitests/policy_files/iam-policy.json
- Validate IAM Policies before they are getting created and stored.
[EOS-25710](https://jts.seagate.com/browse/EOS-25710) 
[EOS-25961](https://jts.seagate.com/browse/EOS-25961)
> EOS-25961: [IAM Policy] Policy Validations added

- scripts/provisioning/configcmd.py
- scripts/provisioning/setupcmd.py
> Common code for service framework

- s3mempoolmgrut/s3_mem_pool_mgr_test.cc
- server/s3_addb_map_auto.c
- server/s3_bucket_counters.cc
- server/s3_bucket_counters.h
- server/s3_copy_object_action.cc
- server/s3_copy_object_action.h
- server/s3_delete_multiple_objects_action.cc
- server/s3_delete_multiple_objects_action.h
- server/s3_delete_object_action.cc
- server/s3_delete_object_action.h
- server/s3_post_complete_action.cc
- server/s3_post_complete_action.h
- server/s3_put_chunk_upload_object_action.cc
- server/s3_put_chunk_upload_object_action.h
- server/s3_put_object_action.cc
- server/s3_put_object_action.h
- server/s3server.cc
- ut/s3_delete_multiple_objects_action_test.cc
- ut/s3_server_tests.cc
- ut_death_tests/s3_server_tests.cc
Estimate the size of bytes consumed by an account/bucket.
Save/Increment/decrement total object size after every object operation
> [EOS-26466] Changes for Bucket capacity counting (Happy Path)

- server/s3_object_metadata.cc
- server/s3_object_metadata.h
- server/s3_put_replication_body.cc
- server/s3_put_replication_body.h
- ut/s3_object_metadata_test.cc
- Improvements in PutObject APIs - handling multiple rules with multiple destination buckets
> [Replication]EOS:26291 Improvements in PutObject APIs - handling multiple rules

- server/s3_object_metadata.cc
- Patch for - EOS:26291 Improvements in PutObject APIs - handling multiple rules.
> [Replication]EOS:26291:PutObject upgrade patch 

- scripts/provisioning/configcmd.py
tk8s mini provisioner job failure fixes
-----
[View rendered docs/notes.md](https://github.com/Seagate/cortx-s3server/blob/br/vr/tk8s-failure/docs/notes.md)
[View rendered s3backgrounddelete/readme.md](https://github.com/Seagate/cortx-s3server/blob/br/vr/tk8s-failure/s3backgrounddelete/readme.md)
> tk8s mini provisioner job failure fixes

- auth/server/src/main/java/com/seagates3/authserver/AuthServerConfig.java
- auth/server/src/main/java/com/seagates3/controller/UserPolicyController.java
- auth/server/src/main/java/com/seagates3/dao/DAOResource.java
- auth/server/src/main/java/com/seagates3/dao/UserPolicyDAO.java
- auth/server/src/main/java/com/seagates3/dao/ldap/AuthStore.java
- auth/server/src/main/java/com/seagates3/dao/ldap/FileStore.java
- auth/server/src/main/java/com/seagates3/dao/ldap/LdapStore.java
- auth/server/src/main/java/com/seagates3/dao/ldap/MotrStore.java
- auth/server/src/main/java/com/seagates3/dao/ldap/UserImpl.java
- auth/server/src/main/java/com/seagates3/dao/ldap/UserPolicyImpl.java
- auth/server/src/main/java/com/seagates3/dao/ldap/UserPolicyLdapStore.java
- auth/server/src/main/java/com/seagates3/exception/GuardClauseException.java
- auth/server/src/main/java/com/seagates3/model/User.java
- auth/server/src/main/java/com/seagates3/model/UserPolicy.java
- auth/server/src/main/java/com/seagates3/parameter/validator/UserPolicyParameterValidator.java
- auth/server/src/main/java/com/seagates3/response/formatter/AbstractResponseFormatter.java
- auth/server/src/main/java/com/seagates3/response/formatter/xml/XMLResponseFormatter.java
- auth/server/src/main/java/com/seagates3/response/generator/UserPolicyResponseGenerator.java
- auth/server/src/main/resources/IAMroutes.json
- auth/server/src/test/java/com/seagates3/dao/ldap/UserImplTest.java
Signed-off-by: Shri Metta <shri.metta@seagate.com>
- Attach policy to user
-  https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/706805920/UML+Diagrams
> [iam policy] EOS-25962: Attach policy to user

- s3config-test.yaml
- s3config.release.yaml.sample
- s3config.yaml.sample
> [EOS-24400] Enable DI in s3 repo

- scripts/provisioning/configcmd.py
> EOS-26780: Fixed the rebase issue

- scripts/provisioning/upgradecmd.py
- scripts/swupdate/merge.py
> EOS-26569 : logging changes to enable merge logging

- scripts/provisioning/configcmd.py
- scripts/provisioning/s3_prov_config.yaml
> EOS-26573:S3: Handle consul endpoint and port values in config phase

- scripts/swupdate/merge.py
> EOS-26569 - Fix for bug in merge file

- scripts/provisioning/configcmd.py
- scripts/provisioning/setupcmd.py
- Service Validation fixes
- Consul re-arange
- BG worker/consumer service changes for partition count
- 
-----
[View rendered docs/notes.md](https://github.com/Seagate/cortx-s3server/blob/br/vr/EOS-26572-II/docs/notes.md)
[View rendered s3backgrounddelete/readme.md](https://github.com/Seagate/cortx-s3server/blob/br/vr/EOS-26572-II/s3backgrounddelete/readme.md)
> EOS-26572: Service Validation fixes

- server/s3_motr_kvs_writer.cc
- server/s3_motr_kvs_writer.h
- server/s3_motr_rw_common.cc
- server/s3_motr_rw_common.h
- ut/mock_s3_motr_kvs_writer.h
- ut/motr_put_key_value_action_test.cc
- ut/s3_abort_multipart_test.cc
- ut/s3_bucket_metadata_v1_test.cc
- ut/s3_delete_object_action_test.cc
- ut/s3_global_bucket_index_metadata_test.cc
- ut/s3_object_metadata_test.cc
- ut/s3_part_metadata_test.cc
- ut/s3_post_complete_action_test.cc
- ut/s3_put_chunk_upload_object_action_test.cc
- ut/s3_put_multiobject_action_test.cc
- ut/s3_put_object_action_test.cc
> [EOS-26464] : [F-22A] DTM: Support for Executed callback in s3

- ut/s3_put_object_action_test.cc
Signed-off-by: Keith Pine <keith.pine@seagate.com>
A unit test was failing after a rebase.
Add necessary mock expectations for new code paths.
-  [X] Coding conventions are followed and code is consistent
> Fix unit test failing after rebase

- scripts/provisioning/setupcmd.py
- S3 producer and worker names are wrongly updated, fixed.
> Update names used in service mapping

- scripts/provisioning/configcmd.py
- scripts/provisioning/initcmd.py
- scripts/provisioning/s3_start
- scripts/provisioning/setupcmd.py
- scripts/provisioning/upgradecmd.py
- Use of Constant service names from cortx-py-utils
> Use of Constant service names from cortx-py-utils

- scripts/env/common/third-party-rpms.txt
- scripts/keepalived/keepalived_config_gen/README.md
- system/s3startsystem.sh
Code has a dependency over PyYAML RPM and Python package.
Reference Bug -> https://jts.seagate.com/browse/EOS-23696
-  [X] Coding conventions are followed and code is consistent
-----
[View rendered scripts/keepalived/keepalived_config_gen/README.md](https://github.com/Seagate/cortx-s3server/blob/swanand-gadre-pyyaml-upgrade-patch-1/scripts/keepalived/keepalived_config_gen/README.md)
> Removing dependency over PyYAML RPM and python package

- scripts/provisioning/configcmd.py
- scripts/provisioning/setupcmd.py
> Service name fix

- server/s3_addb_map_auto.c
Fix error in s3_addb_map_auto.c after sync with kubernetes branch
> Fix build error after sync with kubernetes branch

- s3config.release.yaml.sample
- s3config.yaml.sample
Signed-off-by: Rohit Dwivedi <rohit.k.dwivedi@.seagate.com>
JIRA Story: https://jts.seagate.com/browse/EOS-26020
- Redirect audit log webserver
> EOS-26020: S3 Audit Log Config change for sending audit logs to webserver

- scripts/provisioning/configcmd.py
> [EOS-26900] Make sure config is pushed before proceeding for account creation

- auth-utils/jclient/pom.xml
- auth/encryptcli/pom.xml
- auth/encryptutil/pom.xml
- auth/server/pom.xml
Signed-off-by: Swanand S Gadre <swanand.s.gadre@seagate.com>
One more vulnerability CVE-2021-45105 is reported on log4j
JIRA Bug -> https://jts.seagate.com/browse/EOS-27072
-  [X] Coding conventions are followed and code is consistent
Not applicable
Not applicable
> Upgrade log4j to 2.17.0

- auth/server/src/main/java/com/seagates3/controller/UserPolicyController.java
- auth/server/src/test/java/com/seagates3/controller/UserPolicyControllerTest.java
- st/clitests/awsiam_spec.py
IAM Policy Authorization Bug fixes
-  Bug - ListAttachedUserPolicies API was not working
> [iam-policy] IAM Policy Authorization Bug fixes

- scripts/ldap/cn=s3user.ldif
Signed-off-by: rohitkolapkar <rohit.j.kolapkar@seagate.com>
During rebase of iam-policy with k8s, lost the schema updates required for IAM_policy feature. Due to this build is failing on iam-policy feature branch. 
Failed S3Premerge -> [885](http://eos-jenkins.colo.seagate.com/job/S3server/job/S3Server-PreMerge-Test/885/console)
rebase commit for reference - https://github.com/Seagate/cortx-s3server/pull/1726/commits/942ba207760be57c179a5433f5a3a2d7153c6233 
> [IAM Policy] Build Failure Fix - Updated schema file as per IAM policy requirements

- scripts/provisioning/configcmd.py
- scripts/provisioning/templates/s3.config.tmpl.1-node
- scripts/provisioning/templates/s3.config.tmpl.1-node.sample
- scripts/provisioning/templates/s3.config.tmpl.3-node
- scripts/provisioning/templates/s3.config.tmpl.3-node.sample
- scripts/provisioning/templates/s3.init.tmpl.1-node
- scripts/provisioning/templates/s3.init.tmpl.1-node.sample
- scripts/s3-support-bundles/s3_bundle_generate.sh
- scripts/s3-support-bundles/s3_bundle_generate_service_separation.py
- scripts/s3-support-bundles/s3_bundle_generate_service_separation.sh
Service separation for S3 support bundle
> EOS-25803:  Service separation for S3 support bundle

- server/s3_addb_map_auto.c
- server/s3_api_handler.h
- server/s3_object_api_handler.cc
- server/s3_put_multiobject_copy_action.cc
- server/s3_put_multiobject_copy_action.h
- st/clitests/awss3api.py
- st/clitests/awss3api_spec.py
- ut/s3_object_api_handler_test.cc
- ut/s3_put_multiobject_copy_action_test.cc
Signed-off-by: Sumedh A. Kulkarni <sumedh.a.kulkarni@seagate.com>
> [uploadPartCopy] EOS-24346 : Add ST's & UT's for Upload part copy object.

- auth/server/src/main/java/com/seagates3/parameter/validator/AccessKeyParameterValidator.java
Signed-off-by: rohitkolapkar <rohit.j.kolapkar@seagate.com>
> [IAM Policy] Fix Build Failure due to clang formatting

- ansible/files/yum.repos.d/centos7.9.2009/cortx.repo
- Utils new repo uses infrastructure that is dependent on initialization, so temporarily pointing it old one.
> EOS-27228 - Update repo link to point to old to avoid failures.

- scripts/env/common/third-party-rpms.txt
- scripts/keepalived/keepalived_config_gen/README.md
- system/s3startsystem.sh
Signed-off-by: Sandeep Anjara <sandeep.anjara@seagate.com>
- Custom build with feature branch is failing
-  Remove PyYAML dependency 
-----
[View rendered scripts/keepalived/keepalived_config_gen/README.md](https://github.com/sandeepsgt/cortx-s3server/blob/multipart-uploadPartCopy/scripts/keepalived/keepalived_config_gen/README.md)
> EOS-26897: Remove PyYAML dependency

- ansible/files/yum.repos.d/centos7.9.2009/cortx.repo
> Repo link update

- scripts/s3-support-bundles/s3_bundle_generate.sh
- scripts/s3-support-bundles/s3_bundle_generate_service_separation.py
- scripts/s3-support-bundles/s3_bundle_generate_service_separation.sh
- As per new design include optional parameters in support bundle script.
> EOS-26859 - Include optional parameters in support bundle script

- ansible/files/yum.repos.d/centos7.9.2009/cortx.repo
- s3backgrounddelete/s3backgrounddelete/config/s3_background_delete_config.yaml.sample
- s3backgrounddelete/s3backgrounddelete/config/s3backgrounddelete_unsafe_attributes.yaml
- s3backgrounddelete/s3backgrounddelete/cortx_s3_config.py
- s3backgrounddelete/s3backgrounddelete/object_recovery_msgbus.py
- s3backgrounddelete/s3backgrounddelete/object_recovery_processor.py
- s3backgrounddelete/s3backgrounddelete/object_recovery_scheduler.py
- s3cortxutils/s3msgbus/s3msgbus/cortx_s3_msgbus.py
- scripts/kafka/install-kafka.sh
- scripts/provisioning/configcmd.py
- scripts/provisioning/s3_prov_config.yaml
- scripts/provisioning/s3_start
- server/s3_object_data_copier.cc
- server/s3_object_data_copier.h
- server/s3_put_multiobject_copy_action.cc
- server/s3_put_multiobject_copy_action.h
Signed-off-by: Sandeep Anjara <sandeep.anjara@seagate.com>
> [multipart-partcopy] EOS-27129: Part Copy Based on Specified Range for Multipart Objects

- auth/server/src/main/java/com/seagates3/controller/AccountController.java
- auth/server/src/main/java/com/seagates3/dao/ldap/AccountImpl.java
- auth/server/src/test/java/com/seagates3/controller/AccountControllerTest.java
> Delete Account Failure

- auth/server/src/main/java/com/seagates3/controller/AccountController.java
> Delete Account failure refix
